#ifndef GLYPHCODES_H
#define GLYPHCODES_H
// This file is automatically generated, do not edit it,
// see ./prepare_fonts/README.md for more information. 

// mapping tables use this many bits to store character index
#define TRANSFORMBITS (7)

// mapping tables use this many bits to store transform index
#define CHARBITS (9)

// maximum number of base glyphs supported
#define MAXNCHAR (1<<CHARBITS)

// maximum number of transformation codes that can be supported
#define MAXNMODS (1<<TRANSFORMBITS)


////////////////////////////////////////////////////////////////////////////////
// Transformation command codes:
#define T_GA     (512) // GRAVE_ACCENT (combining modifier)
#define T_AA     (1024) // ACUTE_ACCENT (combining modifier)
#define T_XA     (1536) // CIRCUMFLEX_ACCENT (combining modifier)
#define T_XB     (2048) // CIRCUMFLEX_ACCENT_BELOW (combining modifier)
#define T_TA     (2560) // TILDE (combining modifier)
#define T_MA     (3072) // MACRON (combining modifier)
#define T_OBA    (3584) // OVERLINE (combining modifier)
#define T_BA     (4096) // BREVE (combining modifier)
#define T_OA     (4608) // DOT_ABOVE (combining modifier)
#define T_DA     (5120) // DIAERESIS (combining modifier)
#define T_RA     (5632) // RING_ABOVE (combining modifier)
#define T_DAA    (6144) // DOUBLE_ACUTE_ACCENT (combining modifier)
#define T_CRA    (6656) // CARON (combining modifier)
#define T_DGA    (7168) // DOUBLE_GRAVE_ACCENT (combining modifier)
#define T_IBA    (7680) // INVERTED_BREVE (combining modifier)
#define T_CMB    (8192) // COMMA_BELOW (combining modifier)
#define T_CDL    (8704) // CEDILLA (combining modifier)
#define T_FRMT   (9216) // FERMATA (combining modifier)
#define T_HKAB   (9728) // HOOK_ABOVE (combining modifier)
#define T_OBLW   (10240) // DOT_BELOW (combining modifier)
#define T_LBLW   (10752) // LINE_BELOW (combining modifier)
#define T_TBLW   (11264) // TILDE_BELOW (combining modifier)
#define T_BBLW   (11776) // BREVE_BELOW (combining modifier)
#define T_DBLW   (12288) // DIAERESIS_BELOW (combining modifier)
#define T_RHRA   (12800) // RIGHT_HALF_RING_ABOVE (combining modifier)
#define T_GDT    (13312) // GREEK_DIALYTIKA_TONOS (combining modifier)
#define T_DVLB   (13824) // DOUBLE_VERTICAL_LINE_BELOW (combining modifier)
#define T_MBLW   (14336) // MACRON_BELOW (combining modifier)
#define T_SVSM   (14848) // SEMIVOICED_SOUND_MARK (combining modifier)
#define T_VSM    (15360) // VOICED_SOUND_MARK (combining modifier)
#define T_LHRA   (15872) // LEFT_HALF_RING_ABOVE (combining modifier)
#define T_AEM    (16384) // EMPHASIS_MARK (combining modifier)
#define T_AEP    (16896) // EXCLAMATION_MARK (combining modifier)
#define T_AQM    (17408) // QUESTION_MARK (combining modifier)
#define T_DICB   (17920) // DEVANAGARI_INVERTED_CANDRABINDU (combining modifier)
#define T_DCB    (18432) // DEVANAGARI_CANDRABINDU (combining modifier)
#define T_DSAN   (18944) // DEVANAGARI_ANUSVARA (combining modifier)
#define T_DSOE   (19456) // DEVANAGARI_OE (combining modifier)
#define T_DSNK   (19968) // DEVANAGARI_NUKTA (combining modifier)
#define T_DVSU   (20480) // DEVANAGARI_U (combining modifier)
#define T_DSUU   (20992) // DEVANAGARI_UU (combining modifier)
#define T_DSVR   (21504) // DEVANAGARI_VOCALIC_R (combining modifier)
#define T_DSRR   (22016) // DEVANAGARI_VOCALIC_RR (combining modifier)
#define T_DSCE   (22528) // DEVANAGARI_CANDRA_E (combining modifier)
#define T_DSSR   (23040) // DEVANAGARI_SHORT_E (combining modifier)
#define T_DSE    (23552) // DEVANAGARI_E (combining modifier)
#define T_DSAI   (24064) // DEVANAGARI_AI (combining modifier)
#define T_DSUD   (24576) // DEVANAGARI_UDATTA (combining modifier)
#define T_DSAU   (25088) // DEVANAGARI_ANUDATTA (combining modifier)
#define T_DSAA   (25600) // DEVANAGARI_ACUTE (combining modifier)
#define T_DCEE   (26112) // DEVANAGARI_VOWEL_CANDRA_LONG_E (combining modifier)
#define T_DSUE   (26624) // DEVANAGARI_UE (combining modifier)
#define T_DUUE   (27136) // DEVANAGARI_UUE (combining modifier)
#define T_DSVL   (27648) // DEVANAGARI_VOCALIC_L (combining modifier)
#define T_DSLL   (28160) // DEVANAGARI_VOCALIC_LL (combining modifier)
#define T_H5     (28672) // HREFLECTMAG
#define T_H6     (29184) // HREFLECTMIN
#define T_VU     (29696) // VREFLECTMAG
#define T_VL     (30208) // VREFLECTMIN
#define T_TU     (30720) // TURNMAG
#define T_TL     (31232) // TURNMIN
#define T_MDL    (31744) // MIDDLE_DOT_LOWER
#define T_MDR    (32256) // MIDDLE_DOT_RIGHT
#define T_MDU    (32768) // MIDDLE_DOT_UPPER
#define T_AAUL   (33280) // ACUTE_ACCENT_LEFT
#define T_CDAL   (33792) // CEDILLA_ABOVE_LOWER
#define T_DSU    (34304) // DIAGONAL_STROKE_UPPER
#define T_DSL    (34816) // DIAGONAL_STROKE_LOWER
#define T_ONR    (35328) // OGONEK_RIGHT
#define T_ONM    (35840) // OGONEK_MIDDLE
#define T_RAV    (36352) // CARON_VARIANT
#define T_HK1    (36864) // LOWER_RIGHT_TAIL
#define T_HK2    (37376) // HOOK_2
#define T_HK3    (37888) // PALATAL_HOOK
#define T_AALL   (38400) // APOSTROPHE_ABOVE_LEFT_LOWER
#define T_SMLFH  (38912) // STROKE_MID_LEFT_HALF
#define T_SUMLH  (39424) // STROKE_UPPER_MID_RIGHT_HALF
#define T_SUF    (39936) // STROKE_UPPER_FULL
#define T_SMF    (40448) // STROKE_MIDDLE_FULL
#define T_SULH   (40960) // STROKE_UPPER_LEFT_HALF
#define T_LDS    (41472) // DIAGONAL_STROKE_LEFT
#define T_DSM    (41984) // DIAGONAL_STROKE_MID
#define T_SMMH   (42496) // STROKE_MID_MID_HALF
#define T_SMLH   (43008) // STROKE_MID_LOWER_HALF
#define T_DS1    (43520) // RIGHT_DESCENDER
#define T_MRD    (44032) // MIDRIGHT_DESCENDER
#define T_KDS    (44544) // KDIAGONAL_STROKE
#define T_LDSC   (45056) // LEFT_DESCENDER
#define T_LVT    (45568) // LVERTTICK
#define T_LHU    (46080) // LEFT_HOOK_UPPER
#define T_RHU    (46592) // RIGHT_HOOK_UPPER
#define T_BLD    (47104) // BOLD
#define T_VBD    (47616) // VERYBOLD
#define T_TMB    (48128) // ENTOMB
#define T_ITA    (48640) // ITALIC
#define T_OLN    (49152) // OUTLINE
#define T_EP2    (49664) // EXTENDED_CODEPAGE_2


////////////////////////////////////////////////////////////////////////////////
// Indecies for various glyphs "G_" into the bitmap code page
#define  _COMB_ (  1) // Code to support aliasing combining marks
#define  G_SPAC (  2) // 0x00000020 space
#define  G_RHWB (  3) // 0x000021C0 rightwards harpoon with barb upwards
#define  G_MULS (  4) // 0x000000D7 multiplication sign
#define    G_AL (  5) // 0x00000061 latin small letter a
#define    G_CL (  6) // 0x00000063 latin small letter c
#define    G_EL (  7) // 0x00000065 latin small letter e
#define    G_ML (  8) // 0x0000006D latin small letter m
#define    G_NL (  9) // 0x0000006E latin small letter n
#define    G_OL ( 10) // 0x0000006F latin small letter o
#define    G_RL ( 11) // 0x00000072 latin small letter r
#define    G_SL ( 12) // 0x00000073 latin small letter s
#define    G_UL ( 13) // 0x00000075 latin small letter u
#define    G_VL ( 14) // 0x00000076 latin small letter v
#define    G_WL ( 15) // 0x00000077 latin small letter w
#define    G_XL ( 16) // 0x00000078 latin small letter x
#define    G_ZL ( 17) // 0x0000007A latin small letter z
#define   G_NOS ( 18) // 0x000000AC not sign
#define   G_AEL ( 19) // 0x000000E6 latin small letter ae
#define   G_DIL ( 20) // 0x00000131 latin small letter dotless i
#define  G_KRAL ( 21) // 0x00000138 latin small letter kra
#define  G_AL2L ( 22) // 0x00000251 latin small letter alpha
#define   G_O2L ( 23) // 0x0000025B latin small letter open e
#define   G_TWL ( 24) // 0x0000028D latin small letter turned w
#define   G_PDL ( 25) // 0x00000377 greek small letter pamphylian digamma
#define  G_ALPL ( 26) // 0x000003B1 greek small letter alpha
#define  G_IOTL ( 27) // 0x000003B9 greek small letter iota
#define   G_PIL ( 28) // 0x000003C0 greek small letter pi
#define  G_SIGL ( 29) // 0x000003C3 greek small letter sigma
#define  G_TAUL ( 30) // 0x000003C4 greek small letter tau
#define  G_OMEL ( 31) // 0x000003C9 greek small letter omega
#define   G_PSM ( 32) // 0x000003D6 greek pi symbol
#define  G_KAPM ( 33) // 0x000003F0 greek kappa symbol
#define  G_LUEM ( 34) // 0x000003F5 greek lunate epsilon symbol
#define  G_GHEL ( 35) // 0x00000433 cyrillic small letter ghe
#define  G_ZHEL ( 36) // 0x00000436 cyrillic small letter zhe
#define   G_ELL ( 37) // 0x0000043B cyrillic small letter el
#define   G_ENL ( 38) // 0x0000043D cyrillic small letter en
#define   G_TEL ( 39) // 0x00000442 cyrillic small letter te
#define  G_CHEL ( 40) // 0x00000447 cyrillic small letter che
#define  G_YERL ( 41) // 0x0000044B cyrillic small letter yeru
#define  G_IZHL ( 42) // 0x00000475 cyrillic small letter izhitsa
#define    G_GL ( 43) // 0x00000067 latin small letter g
#define    G_PL ( 44) // 0x00000070 latin small letter p
#define    G_QL ( 45) // 0x00000071 latin small letter q
#define    G_YL ( 46) // 0x00000079 latin small letter y
#define  G_MICS ( 47) // 0x000000B5 micro sign
#define  G_NWLL ( 48) // 0x0000019E latin small letter n with long right leg
#define   G_DJL ( 49) // 0x00000237 latin small letter dotless j
#define  G_EZHL ( 50) // 0x00000292 latin small letter ezh
#define  G_GAML ( 51) // 0x000003B3 greek small letter gamma
#define  G_RHOL ( 52) // 0x000003C1 greek small letter rho
#define   G_FSL ( 53) // 0x000003C2 greek small letter final sigma
#define  G_PH2L ( 54) // 0x000003C6 greek small letter phi
#define  G_CHIL ( 55) // 0x000003C7 greek small letter chi
#define  G_RHSM ( 56) // 0x000003F1 greek rho symbol
#define   G_YIL ( 57) // 0x00000575 armenian small letter yi
#define  G_EXCM ( 58) // 0x00000021 exclamation mark
#define  G_DIG0 ( 59) // 0x00000030 digit 0
#define  G_DIG1 ( 60) // 0x00000031 digit 1
#define  G_DIG2 ( 61) // 0x00000032 digit 2
#define  G_DIG3 ( 62) // 0x00000033 digit 3
#define  G_DIG4 ( 63) // 0x00000034 digit 4
#define  G_DIG5 ( 64) // 0x00000035 digit 5
#define  G_DIG6 ( 65) // 0x00000036 digit 6
#define  G_DIG7 ( 66) // 0x00000037 digit 7
#define  G_DIG8 ( 67) // 0x00000038 digit 8
#define  G_DIG9 ( 68) // 0x00000039 digit 9
#define  G_LESS ( 69) // 0x0000003C less-than sign
#define  G_QUEM ( 70) // 0x0000003F question mark
#define    G_AU ( 71) // 0x00000041 latin capital letter a
#define    G_BU ( 72) // 0x00000042 latin capital letter b
#define    G_CU ( 73) // 0x00000043 latin capital letter c
#define    G_DU ( 74) // 0x00000044 latin capital letter d
#define    G_EU ( 75) // 0x00000045 latin capital letter e
#define    G_FU ( 76) // 0x00000046 latin capital letter f
#define    G_GU ( 77) // 0x00000047 latin capital letter g
#define    G_HU ( 78) // 0x00000048 latin capital letter h
#define    G_IU ( 79) // 0x00000049 latin capital letter i
#define    G_JU ( 80) // 0x0000004A latin capital letter j
#define    G_KU ( 81) // 0x0000004B latin capital letter k
#define    G_LU ( 82) // 0x0000004C latin capital letter l
#define    G_MU ( 83) // 0x0000004D latin capital letter m
#define    G_NU ( 84) // 0x0000004E latin capital letter n
#define    G_OU ( 85) // 0x0000004F latin capital letter o
#define    G_PU ( 86) // 0x00000050 latin capital letter p
#define    G_RU ( 87) // 0x00000052 latin capital letter r
#define    G_SU ( 88) // 0x00000053 latin capital letter s
#define    G_TU ( 89) // 0x00000054 latin capital letter t
#define    G_UU ( 90) // 0x00000055 latin capital letter u
#define    G_VU ( 91) // 0x00000056 latin capital letter v
#define    G_WU ( 92) // 0x00000057 latin capital letter w
#define    G_XU ( 93) // 0x00000058 latin capital letter x
#define    G_YU ( 94) // 0x00000059 latin capital letter y
#define    G_ZU ( 95) // 0x0000005A latin capital letter z
#define  G_LDAQ ( 96) // 0x000000AB left-pointing double angle quotation mark
#define  G_PLU2 ( 97) // 0x000000B1 plus-minus sign
#define   G_AEU ( 98) // 0x000000C6 latin capital letter ae
#define  G_BWTU ( 99) // 0x00000182 latin capital letter b with topbar
#define  G_SCHU (100) // 0x0000018F latin capital letter schwa
#define  G_OWMU (101) // 0x0000019F latin capital letter o with middle tilde
#define  G_ESHU (102) // 0x000001A9 latin capital letter esh
#define  G_EZHU (103) // 0x000001B7 latin capital letter ezh
#define    G_DC (104) // 0x000001C0 latin letter dental click
#define   G_DZU (105) // 0x000001F1 latin capital letter dz
#define G_DWSLU (106) // 0x000001F2 latin capital letter d with small letter z
#define   G_TVU (107) // 0x00000245 latin capital letter turned v
#define   G_PDU (108) // 0x00000376 greek capital letter pamphylian digamma
#define  G_GAMU (109) // 0x00000393 greek capital letter gamma
#define  G_DELU (110) // 0x00000394 greek capital letter delta
#define   G_XIU (111) // 0x0000039E greek capital letter xi
#define   G_PIU (112) // 0x000003A0 greek capital letter pi
#define  G_PHIU (113) // 0x000003A6 greek capital letter phi
#define  G_PSIU (114) // 0x000003A8 greek capital letter psi
#define  G_OMEU (115) // 0x000003A9 greek capital letter omega
#define  G_LAML (116) // 0x000003BB greek small letter lamda
#define  G_UWHM (117) // 0x000003D2 greek upsilon with hook symbol
#define   G_UIU (118) // 0x00000404 cyrillic capital letter ukrainian ie
#define  G_ZHEU (119) // 0x00000416 cyrillic capital letter zhe
#define   G_ELU (120) // 0x0000041B cyrillic capital letter el
#define    G_2U (121) // 0x00000423 cyrillic capital letter u
#define  G_CHEU (122) // 0x00000427 cyrillic capital letter che
#define  G_YERU (123) // 0x0000042B cyrillic capital letter yeru
#define   G_S2U (124) // 0x0000042C cyrillic capital letter soft sign
#define  G_OM2U (125) // 0x00000460 cyrillic capital letter omega
#define  G_IZHU (126) // 0x00000474 cyrillic capital letter izhitsa
#define  G_BENU (127) // 0x00000532 armenian capital letter ben
#define  G_GIMU (128) // 0x00000533 armenian capital letter gim
#define  G_GHAU (129) // 0x00000542 armenian capital letter ghad
#define     G_A (130) // 0x00000905 devanagari letter a
#define    G_AA (131) // 0x00000906 devanagari letter aa
#define   G_MVL (132) // 0x00001EFD latin small letter middle-welsh v
#define  G_UPWA (133) // 0x00002191 upwards arrow
#define  G_RIGA (134) // 0x00002192 rightwards arrow
#define  G_NOWA (135) // 0x00002196 north west arrow
#define  G_D2HA (136) // 0x000021A1 downwards 2 headed arrow
#define  G_UAWT (137) // 0x000021B0 upwards arrow with tip leftwards
#define  G_ATSA (138) // 0x000021B6 anticlockwise top semicircle arrow
#define  G_AOCA (139) // 0x000021BA anticlockwise open circle arrow
#define  G_UHWB (140) // 0x000021BF upwards harpoon with barb leftwards
#define  G_UPDA (141) // 0x000021E1 upwards dashed arrow
#define  G_RIDA (142) // 0x000021E2 rightwards dashed arrow
#define  G_RIOA (143) // 0x000021FE rightwards open-headed arrow
#define  G_PARD (144) // 0x00002202 partial differential
#define  G_NABL (145) // 0x00002207 nabla
#define  G_GOET (146) // 0x00002265 greater-than or equal to
#define  G_NTFS (147) // 0x00002491 number ten full stop
#define  G_NEFS (148) // 0x00002492 number eleven full stop
#define  G_NTF2 (149) // 0x00002493 number twelve full stop
#define  G_NTF3 (150) // 0x00002494 number thirteen full stop
#define  G_N4FS (151) // 0x00002495 number 4teen full stop
#define  G_NFFS (152) // 0x00002496 number fifteen full stop
#define  G_N6FS (153) // 0x00002497 number 6teen full stop
#define  G_N7FS (154) // 0x00002498 number 7teen full stop
#define  G_N8FS (155) // 0x00002499 number 8een full stop
#define  G_N9FS (156) // 0x0000249A number 9teen full stop
#define  G_NTF4 (157) // 0x0000249B number twenty full stop
#define  G_BLUT (158) // 0x000025B2 black up-pointing triangle
#define  G_BLRT (159) // 0x000025B6 black right-pointing triangle
#define  G_BLAD (160) // 0x000025C6 black diamond
#define  G_WHIC (161) // 0x000025CB white circle
#define  G_BLSF (162) // 0x0000263B black smiling face
#define  G_BLSS (163) // 0x00002660 black spade suit
#define  G_BLCS (164) // 0x00002663 black club suit
#define  G_BLHS (165) // 0x00002665 black heart suit
#define  G_CHEM (166) // 0x00002713 check mark
#define  G_TTRA (167) // 0x000027A2 three-d top-lighted rightwards arrowhead
#define  G_LBDR (168) // 0x0000294B left barb down right barb up harpoon
#define  G_UBLD (169) // 0x0000294D up barb left down barb right harpoon
#define  G_UPTA (170) // 0x00002B61 upwards triangle-headed arrow
#define  G_TRUE (171) // 0x00002B99 three-d right-lighted upwards equilateral arrowhead
#define  G_D2AW (172) // 0x00002BEF downwards 2-headed arrow with triangle arrowheads
#define   G_YNU (173) // 0x0000A65E cyrillic capital letter yn
#define  G_WRPB (174) // 0x0001F449 white right pointing backhand index
#define  G_THUS (175) // 0x0001F44D thumbs up sign
#define  G_UPSA (176) // 0x0001F839 upwards squared arrow
#define  G_RISA (177) // 0x0001F83A rightwards squared arrow
#define  G_UPCA (178) // 0x0001F83D upwards compressed arrow
#define  G_WSEB (179) // 0x0001F86E wide-headed south east barb arrow
#define    G_QU (180) // 0x00000051 latin capital letter q
#define  G_DVSA (181) // 0x0000093E devanagari vowel sign aa
#define  G_DOLS (182) // 0x00000024 dollar sign
#define    G_BL (183) // 0x00000062 latin small letter b
#define    G_DL (184) // 0x00000064 latin small letter d
#define    G_FL (185) // 0x00000066 latin small letter f
#define    G_HL (186) // 0x00000068 latin small letter h
#define    G_IL (187) // 0x00000069 latin small letter i
#define    G_KL (188) // 0x0000006B latin small letter k
#define    G_LL (189) // 0x0000006C latin small letter l
#define    G_TL (190) // 0x00000074 latin small letter t
#define  G_PILS (191) // 0x000000B6 pilcrow sign
#define   G_LSL (192) // 0x0000017F latin small letter long s
#define   G_DZL (193) // 0x000001F3 latin small letter dz
#define   G_DDL (194) // 0x00000238 latin small letter db digraph
#define  G_DELL (195) // 0x000003B4 greek small letter delta
#define  G_THEL (196) // 0x000003B8 greek small letter theta
#define  G_THEM (197) // 0x000003D1 greek theta symbol
#define  G_SHIN (198) // 0x000010E8 georgian letter shin
#define   G_JIL (199) // 0x000010EB georgian letter jil
#define   G_MVU (200) // 0x00001EFC latin capital letter middle-welsh v
#define  G_CCCA (201) // 0x00002941 clockwise closed circle arrow
#define  G_UPHA (202) // 0x0001F845 upwards heavy arrow
#define  G_LEFP (203) // 0x00000028 left parenthesis
#define  G_SOLI (204) // 0x0000002F solidus
#define  G_LESB (205) // 0x0000005B left square bracket
#define    G_JL (206) // 0x0000006A latin small letter j
#define  G_LECB (207) // 0x0000007B left curly bracket
#define  G_FWHL (208) // 0x00000192 latin small letter f with hook
#define  G_PHIL (209) // 0x00000278 latin small letter phi
#define  G_BETL (210) // 0x000003B2 greek small letter beta
#define  G_ZETL (211) // 0x000003B6 greek small letter zeta
#define   G_XIL (212) // 0x000003BE greek small letter xi
#define  G_PSIL (213) // 0x000003C8 greek small letter psi
#define   G_UDA (214) // 0x00002195 up down arrow
#define  G_BALX (215) // 0x00002717 ballot x
#define  G_RHCA (216) // 0x0001F842 rightwards heavy compressed arrow
#define  G_WUPB (217) // 0x0001F446 white up pointing backhand index
#define  G_KAIM (218) // 0x000030FD katakana iteration mark
#define    G_K8 (219) // 0x00003053 hiragana letter ko
#define    G_T6 (220) // 0x00003064 hiragana letter tu
#define    G_T7 (221) // 0x00003066 hiragana letter te
#define    G_H6 (222) // 0x00003072 hiragana letter hi
#define    G_H4 (223) // 0x00003078 hiragana letter he
#define  G_HIIM (224) // 0x0000309D hiragana iteration mark
#define    G_KO (225) // 0x000030B3 katakana letter ko
#define    G_S3 (226) // 0x000030B9 katakana letter su
#define    G_SO (227) // 0x000030BD katakana letter so
#define    G_T3 (228) // 0x000030C4 katakana letter tu
#define    G_TO (229) // 0x000030C8 katakana letter to
#define    G_H2 (230) // 0x000030CF katakana letter ha
#define    G_HI (231) // 0x000030D2 katakana letter hi
#define    G_H3 (232) // 0x000030D5 katakana letter hu
#define    G_WA (233) // 0x000030EF katakana letter wa
#define    G_W2 (234) // 0x000030F1 katakana letter we
#define    G_WO (235) // 0x000030F2 katakana letter wo
#define     G_E (236) // 0x0000090F devanagari letter e
#define    G_KA (237) // 0x00000915 devanagari letter ka
#define   G_KHA (238) // 0x00000916 devanagari letter kha
#define    G_GA (239) // 0x00000917 devanagari letter ga
#define    G_JA (240) // 0x0000091C devanagari letter ja
#define   G_DDA (241) // 0x00000921 devanagari letter dda
#define  G_DDHA (242) // 0x00000922 devanagari letter ddha
#define    G_NA (243) // 0x00000928 devanagari letter na
#define   G_PHA (244) // 0x0000092B devanagari letter pha
#define    G_YA (245) // 0x0000092F devanagari letter ya
#define    G_RA (246) // 0x00000930 devanagari letter ra
#define   G_LLA (247) // 0x00000933 devanagari letter lla
#define  G_LERA (248) // 0x00002194 left right arrow
#define  G_R2HA (249) // 0x000021A0 rightwards 2 headed arrow
#define  G_RID2 (250) // 0x000021D2 rightwards double arrow
#define  G_R2AW (251) // 0x00002BEE rightwards 2-headed arrow with triangle arrowheads
#define  G_RIHA (252) // 0x0001F846 rightwards heavy arrow
#define     G_8 (253) // 0x00003046 hiragana letter u
#define    G_K4 (254) // 0x0000304B hiragana letter ka
#define    G_K5 (255) // 0x0000304D hiragana letter ki
#define    G_K6 (256) // 0x0000304F hiragana letter ku
#define    G_K7 (257) // 0x00003051 hiragana letter ke
#define    G_S4 (258) // 0x00003055 hiragana letter sa
#define    G_S5 (259) // 0x00003057 hiragana letter si
#define    G_S6 (260) // 0x00003059 hiragana letter su
#define    G_S7 (261) // 0x0000305B hiragana letter se
#define    G_S8 (262) // 0x0000305D hiragana letter so
#define    G_T4 (263) // 0x0000305F hiragana letter ta
#define    G_T5 (264) // 0x00003061 hiragana letter ti
#define    G_T8 (265) // 0x00003068 hiragana letter to
#define    G_H5 (266) // 0x0000306F hiragana letter ha
#define    G_H7 (267) // 0x00003075 hiragana letter hu
#define    G_H8 (268) // 0x0000307B hiragana letter ho
#define     G_4 (269) // 0x000030A6 katakana letter u
#define    G_K2 (270) // 0x000030AB katakana letter ka
#define    G_KI (271) // 0x000030AD katakana letter ki
#define    G_K3 (272) // 0x000030AF katakana letter ku
#define    G_KE (273) // 0x000030B1 katakana letter ke
#define    G_S2 (274) // 0x000030B5 katakana letter sa
#define    G_SI (275) // 0x000030B7 katakana letter si
#define    G_SE (276) // 0x000030BB katakana letter se
#define    G_T2 (277) // 0x000030BF katakana letter ta
#define    G_TI (278) // 0x000030C1 katakana letter ti
#define    G_TE (279) // 0x000030C6 katakana letter te
#define    G_HO (280) // 0x000030DB katakana letter ho
#define    G_WI (281) // 0x000030F0 katakana letter wi
#define  G_MLAB (282) // 0x0000276C medium left-pointing angle bracket ornament
#define  G_QUOM (283) // 0x00000022 quotation mark
#define  G_APOS (284) // 0x00000027 apostrophe
#define  G_HYPH (285) // 0x0000002D hyphen-minus
#define  G_CIRA (286) // 0x0000005E circumflex accent
#define  G_GRAA (287) // 0x00000060 grave accent
#define  G_TILD (288) // 0x0000007E tilde
#define  G_DEGS (289) // 0x000000B0 degree sign
#define  G_SUP2 (290) // 0x000000B2 superscript 2
#define  G_SUP3 (291) // 0x000000B3 superscript 3
#define  G_SUP1 (292) // 0x000000B9 superscript 1
#define  G_CSFP (293) // 0x00001429 canadian syllabics final plus
#define  G_CSWF (294) // 0x0000167E canadian syllabics woods-cree final th
#define  G_SUP0 (295) // 0x00002070 superscript 0
#define    G_3L (296) // 0x00002071 superscript latin small letter i
#define  G_SUP4 (297) // 0x00002074 superscript 4
#define  G_SUP5 (298) // 0x00002075 superscript 5
#define  G_SUP6 (299) // 0x00002076 superscript 6
#define  G_SUP7 (300) // 0x00002077 superscript 7
#define  G_SUP8 (301) // 0x00002078 superscript 8
#define  G_SUP9 (302) // 0x00002079 superscript 9
#define  G_SUPM (303) // 0x0000207B superscript minus
#define  G_SULP (304) // 0x0000207D superscript left parenthesis
#define  G_SURP (305) // 0x0000207E superscript right parenthesis
#define    G_2L (306) // 0x0000207F superscript latin small letter n
#define  G_COMM (307) // 0x0000002C comma
#define  G_FULS (308) // 0x0000002E full stop
#define   G_LOL (309) // 0x0000005F low line
#define  G_HORE (310) // 0x00002026 horizontal ellipsis
#define  G_SUB0 (311) // 0x00002080 subscript 0
#define  G_SUB1 (312) // 0x00002081 subscript 1
#define  G_SUB2 (313) // 0x00002082 subscript 2
#define  G_SUB3 (314) // 0x00002083 subscript 3
#define  G_SUB4 (315) // 0x00002084 subscript 4
#define  G_SUB5 (316) // 0x00002085 subscript 5
#define  G_SUB6 (317) // 0x00002086 subscript 6
#define  G_SUB7 (318) // 0x00002087 subscript 7
#define  G_SUB8 (319) // 0x00002088 subscript 8
#define  G_SUB9 (320) // 0x00002089 subscript 9
#define  G_SUPS (321) // 0x0000208A subscript plus sign
#define  G_SUBM (322) // 0x0000208B subscript minus
#define  G_SUES (323) // 0x0000208C subscript equals sign
#define  G_SUL2 (324) // 0x0000208D subscript left parenthesis
#define  G_SUR2 (325) // 0x0000208E subscript right parenthesis
#define  G_EQUS (327) // 0x0000003D equals sign
#define  G_BULL (328) // 0x00002022 bullet
#define  G_INFI (329) // 0x0000221E infinity
#define  G_BLAR (330) // 0x000025AC black rectangle
#define   G_OEL (331) // 0x00000153 latin small ligature oe
#define G_SCBLU (332) // 0x00000299 latin letter small capital b
#define  G_HETL (333) // 0x00000371 greek small letter heta
#define  G_KHEL (334) // 0x000003E7 coptic small letter khei
#define  G_SHAL (335) // 0x00000448 cyrillic small letter sha
#define   G_HSL (336) // 0x0000044A cyrillic small letter hard sign
#define   G_S2L (337) // 0x0000044C cyrillic small letter soft sign
#define   G_YUL (338) // 0x0000044E cyrillic small letter yu
#define   G_YAL (339) // 0x0000044F cyrillic small letter ya
#define  G_LJEL (340) // 0x00000459 cyrillic small letter lje
#define  G_NJEL (341) // 0x0000045A cyrillic small letter nje
#define   G_IEL (342) // 0x00000465 cyrillic small letter iotified e
#define   G_LYL (343) // 0x00000467 cyrillic small letter little yus
#define  G_ILYL (344) // 0x00000469 cyrillic small letter iotified little yus
#define   G_BYL (345) // 0x0000046B cyrillic small letter big yus
#define  G_IBYL (346) // 0x0000046D cyrillic small letter iotified big yus
#define   G_ROL (347) // 0x0000047B cyrillic small letter round omega
#define  G_THOS (348) // 0x00000482 cyrillic thousands sign
#define   G_RAL (349) // 0x0000057C armenian small letter ra
#define  G_TIWL (350) // 0x0000057F armenian small letter tiwn
#define    G_AN (351) // 0x000010D0 georgian letter an
#define    G_IN (352) // 0x000010D8 georgian letter in
#define    G_ON (353) // 0x000010DD georgian letter on
#define  G_ELEO (354) // 0x00002208 element of
#define   G_IAL (355) // 0x0000A657 cyrillic small letter iotified a
#define   G_BOL (356) // 0x0000A66B cyrillic small letter binocular o
#define  G_DMOL (357) // 0x0000A66D cyrillic small letter double monocular o
#define  G_YOGL (359) // 0x0000021D latin small letter yogh
#define  G_GA2L (360) // 0x00000263 latin small letter gamma
#define  G_TMWL (361) // 0x00000270 latin small letter turned m with long leg
#define  G_MWHL (362) // 0x00000271 latin small letter m with hook
#define  G_SHEL (363) // 0x000003E3 coptic small letter shei
#define  G_FEIL (364) // 0x000003E5 coptic small letter fei
#define  G_HORL (365) // 0x000003E9 coptic small letter hori
#define  G_DEIL (366) // 0x000003EF coptic small letter dei
#define   G_DEL (367) // 0x00000434 cyrillic small letter de
#define  G_TSEL (368) // 0x00000446 cyrillic small letter tse
#define  G_SHCL (369) // 0x00000449 cyrillic small letter shcha
#define  G_DZHL (370) // 0x0000045F cyrillic small letter dzhe
#define   G_UKL (371) // 0x00000479 cyrillic small letter uk
#define  G_GWML (372) // 0x00000495 cyrillic small letter ghe with middle hook
#define   G_AHL (373) // 0x000004A9 cyrillic small letter abkhasian ha
#define  G_BENL (374) // 0x00000562 armenian small letter ben
#define  G_GIML (375) // 0x00000563 armenian small letter gim
#define   G_DAL (376) // 0x00000564 armenian small letter da
#define   G_ZAL (377) // 0x00000566 armenian small letter za
#define   G_ETL (378) // 0x00000568 armenian small letter et
#define   G_TOL (379) // 0x00000569 armenian small letter to
#define  G_LIWL (380) // 0x0000056C armenian small letter liwn
#define  G_GHAL (381) // 0x00000572 armenian small letter ghad
#define  G_SH2L (382) // 0x00000577 armenian small letter sha
#define  G_CHAL (383) // 0x00000579 armenian small letter cha
#define  G_JHEL (384) // 0x0000057B armenian small letter jheh
#define  G_KEHL (385) // 0x00000584 armenian small letter keh
#define   G_GAN (386) // 0x000010D2 georgian letter gan
#define   G_DON (387) // 0x000010D3 georgian letter don
#define    G_EN (388) // 0x000010D4 georgian letter en
#define   G_VIN (389) // 0x000010D5 georgian letter vin
#define   G_TAN (390) // 0x000010D7 georgian letter tan
#define   G_KAN (391) // 0x000010D9 georgian letter kan
#define   G_LAS (392) // 0x000010DA georgian letter las
#define  G_ZHAR (393) // 0x000010DF georgian letter zhar
#define    G_UN (394) // 0x000010E3 georgian letter un
#define  G_PHAR (395) // 0x000010E4 georgian letter phar
#define  G_GHAN (396) // 0x000010E6 georgian letter ghan
#define   G_QAR (397) // 0x000010E7 georgian letter qar
#define   G_CAN (398) // 0x000010EA georgian letter can
#define   G_HIE (399) // 0x000010F2 georgian letter hie
#define    G_WE (400) // 0x000010F3 georgian letter we
#define    G_TG (401) // 0x000010F9 georgian letter turned gan
#define    G_RI (402) // 0x000030EA katakana letter ri
#define  G_SHWL (403) // 0x0000A697 cyrillic small letter shwe
#define  G_NUMS (404) // 0x00000023 number sign
#define  G_AMPE (405) // 0x00000026 ampersand
#define  G_ASTE (406) // 0x0000002A asterisk
#define  G_PLUS (407) // 0x0000002B plus sign
#define  G_COLO (408) // 0x0000003A colon
#define  G_SEMI (409) // 0x0000003B semicolon
#define  G_POUS (410) // 0x000000A3 pound sign
#define  G_CURS (411) // 0x000000A4 currency sign
#define   G_YES (412) // 0x000000A5 yen sign
#define  G_FEOI (413) // 0x000000AA feminine ordinal indicator
#define  G_MAOI (414) // 0x000000BA masculine ordinal indicator
#define  G_THOU (415) // 0x000000DE latin capital letter thorn
#define  G_DIVS (416) // 0x000000F7 division sign
#define   G_IJU (417) // 0x00000132 latin capital ligature ij
#define   G_OEU (418) // 0x00000152 latin capital ligature oe
#define  G_GA2U (419) // 0x00000194 latin capital letter gamma
#define    G_LC (420) // 0x000001C1 latin letter lateral click
#define   G_LJU (421) // 0x000001C7 latin capital letter lj
#define   G_OUU (422) // 0x00000222 latin capital letter ou
#define  G_HETU (423) // 0x00000370 greek capital letter heta
#define   G_ASU (424) // 0x00000372 greek capital letter archaic sampi
#define  G_KOPP (425) // 0x000003DE greek letter koppa
#define  G_LJEU (426) // 0x00000409 cyrillic capital letter lje
#define  G_NJEU (427) // 0x0000040A cyrillic capital letter nje
#define  G_TSHU (428) // 0x0000040B cyrillic capital letter tshe
#define  G_SHAU (429) // 0x00000428 cyrillic capital letter sha
#define   G_HSU (430) // 0x0000042A cyrillic capital letter hard sign
#define   G_YUU (431) // 0x0000042E cyrillic capital letter yu
#define   G_BEL (432) // 0x00000431 cyrillic small letter be
#define   G_IEU (433) // 0x00000464 cyrillic capital letter iotified e
#define   G_LYU (434) // 0x00000466 cyrillic capital letter little yus
#define  G_ILYU (435) // 0x00000468 cyrillic capital letter iotified little yus
#define   G_BYU (436) // 0x0000046A cyrillic capital letter big yus
#define  G_IBYU (437) // 0x0000046C cyrillic capital letter iotified big yus
#define   G_ROU (438) // 0x0000047A cyrillic capital letter round omega
#define  G_GWUL (439) // 0x00000491 cyrillic small letter ghe with upturn
#define  G_AYBU (440) // 0x00000531 armenian capital letter ayb
#define   G_DAU (441) // 0x00000534 armenian capital letter da
#define   G_ZAU (442) // 0x00000536 armenian capital letter za
#define   G_EHU (443) // 0x00000537 armenian capital letter eh
#define   G_ETU (444) // 0x00000538 armenian capital letter et
#define   G_TOU (445) // 0x00000539 armenian capital letter to
#define  G_INIU (446) // 0x0000053B armenian capital letter ini
#define  G_XEHU (447) // 0x0000053D armenian capital letter xeh
#define   G_CAU (448) // 0x0000053E armenian capital letter ca
#define  G_KENU (449) // 0x0000053F armenian capital letter ken
#define   G_HOU (450) // 0x00000540 armenian capital letter ho
#define   G_JAU (451) // 0x00000541 armenian capital letter ja
#define  G_CH2U (452) // 0x00000543 armenian capital letter cheh
#define  G_MENU (453) // 0x00000544 armenian capital letter men
#define   G_YIU (454) // 0x00000545 armenian capital letter yi
#define  G_SH2U (455) // 0x00000547 armenian capital letter sha
#define  G_CHAU (456) // 0x00000549 armenian capital letter cha
#define  G_PEHU (457) // 0x0000054A armenian capital letter peh
#define  G_JHEU (458) // 0x0000054B armenian capital letter jheh
#define   G_RAU (459) // 0x0000054C armenian capital letter ra
#define  G_VEWU (460) // 0x0000054E armenian capital letter vew
#define   G_COU (461) // 0x00000551 armenian capital letter co
#define  G_YIWU (462) // 0x00000552 armenian capital letter yiwn
#define  G_KEHU (463) // 0x00000554 armenian capital letter keh
#define  G_FEHU (464) // 0x00000556 armenian capital letter feh
#define  G_ECHL (465) // 0x00000565 armenian small letter ech
#define   G_EHL (466) // 0x00000567 armenian small letter eh
#define   G_CAL (467) // 0x0000056E armenian small letter ca
#define  G_MENL (468) // 0x00000574 armenian small letter men
#define  G_NOWL (469) // 0x00000576 armenian small letter now
#define   G_EYL (470) // 0x00000587 armenian small ligature ech yiwn
#define  G_ARDS (471) // 0x0000058F armenian dram sign
#define   G_DHA (472) // 0x00000927 devanagari letter dha
#define   G_BHA (473) // 0x0000092D devanagari letter bha
#define   G_SHA (474) // 0x00000936 devanagari letter sha
#define  G_DESA (475) // 0x0000093D devanagari sign avagraha
#define  G_GEP2 (476) // 0x000010FB georgian paragraph separator
#define    G_HS (477) // 0x000010FE georgian letter hard sign
#define  G_ETSB (478) // 0x00001260 ethiopic syllable ba
#define  G_DOEM (479) // 0x0000203C double exclamation mark
#define  G_INT2 (480) // 0x0000203D interrobang
#define  G_PESS (481) // 0x000020A7 peseta sign
#define   G_WOS (482) // 0x000020A9 won sign
#define   G_NSS (483) // 0x000020AA new sheqel sign
#define  G_EURS (484) // 0x000020AC euro sign
#define  G_TUGS (485) // 0x000020AE tugrik sign
#define  G_GEPS (486) // 0x000020B0 german penny sign
#define  G_AUSS (487) // 0x000020B3 austral sign
#define  G_INRS (488) // 0x000020B9 indian rupee sign
#define  G_TULS (489) // 0x000020BA turkish lira sign
#define  G_RUBS (490) // 0x000020BD ruble sign
#define  G_ALEM (491) // 0x00002135 alef symbol
#define  G_RON3 (492) // 0x00002162 roman numeral 3
#define  G_RON4 (493) // 0x00002163 roman numeral 4
#define  G_RON6 (494) // 0x00002165 roman numeral 6
#define  G_RON9 (495) // 0x00002168 roman numeral 9
#define  G_RONE (496) // 0x0000216A roman numeral eleven
#define  G_SR6L (497) // 0x00002171 small roman numeral 2
#define  G_SR5L (498) // 0x00002172 small roman numeral 3
#define  G_SR3L (499) // 0x00002173 small roman numeral 4
#define  G_SR4L (500) // 0x00002175 small roman numeral 6
#define  G_SR2L (501) // 0x00002178 small roman numeral 9
#define  G_SRNL (502) // 0x0000217A small roman numeral eleven
#define  G_RN1T (503) // 0x00002180 roman numeral 1 thousand c d
#define  G_RN5T (504) // 0x00002181 roman numeral 5 thousand
#define  G_RNFT (505) // 0x00002187 roman numeral fifty thousand
#define  G_RAWC (506) // 0x000021B4 rightwards arrow with corner downwards
#define   G_EOP (507) // 0x0000220E end of proof
#define  G_RINO (508) // 0x00002218 ring operator
#define  G_RIG2 (509) // 0x0000221F right angle
#define  G_ALET (510) // 0x00002248 almost equal to
#define   G_NET (511) // 0x00002260 not equal to
#define  G_IDET (  0|T_EP2) // 0x00002261 identical to
#define  G_WHIS (  1|T_EP2) // 0x000025A1 white square
#define  G_BLAC (  2|T_EP2) // 0x000025CF black circle
#define  G_BLAS (  3|T_EP2) // 0x00002605 black star
#define  G_CROJ (  4|T_EP2) // 0x00002629 cross of jerusalem
#define  G_WSWR (  5|T_EP2) // 0x0000263C white sun with rays
#define  G_FEMS (  6|T_EP2) // 0x00002640 female sign
#define  G_MALS (  7|T_EP2) // 0x00002642 male sign
#define  G_QUAN (  8|T_EP2) // 0x00002669 quarter note
#define  G_WARS (  9|T_EP2) // 0x000026A0 warning sign
#define  G_OUGC ( 10|T_EP2) // 0x00002719 outlined greek cross
#define  G_TEAA ( 11|T_EP2) // 0x0000273B teardrop-spoked asterisk
#define  G_RHBH ( 12|T_EP2) // 0x00002765 rotated heavy black heart bullet
#define   G_IAU ( 13|T_EP2) // 0x0000A656 cyrillic capital letter iotified a
#define   G_BOU ( 14|T_EP2) // 0x0000A66A cyrillic capital letter binocular o
#define  G_DMOU ( 15|T_EP2) // 0x0000A66C cyrillic capital letter double monocular o
#define   G_STL ( 16|T_EP2) // 0x0000FB06 latin small ligature st
#define  G_HEAD ( 17|T_EP2) // 0x0001F3A7 headphone
#define  G_GHOS ( 18|T_EP2) // 0x0001F47B ghost
#define  G_SKUL ( 19|T_EP2) // 0x0001F480 skull
#define   G_GES ( 20|T_EP2) // 0x0001F48E gem stone
#define  G_MINI ( 21|T_EP2) // 0x0001F4BD minidisc
#define  G_CARI ( 22|T_EP2) // 0x0001F4C7 card index
#define  G_COMA ( 23|T_EP2) // 0x00000040 commercial at
#define  G_CENS ( 24|T_EP2) // 0x000000A2 cent sign
#define   G_NJU ( 25|T_EP2) // 0x000001CA latin capital letter nj
#define  G_YOGU ( 26|T_EP2) // 0x0000021C latin capital letter yogh
#define   G_GSU ( 27|T_EP2) // 0x00000241 latin capital letter glottal stop
#define   G_ASL ( 28|T_EP2) // 0x00000373 greek small letter archaic sampi
#define  G_STIL ( 29|T_EP2) // 0x000003DB greek small letter stigma
#define  G_SAML ( 30|T_EP2) // 0x000003E1 greek small letter sampi
#define  G_FEIU ( 31|T_EP2) // 0x000003E4 coptic capital letter fei
#define  G_HORU ( 32|T_EP2) // 0x000003E8 coptic capital letter hori
#define  G_DEIU ( 33|T_EP2) // 0x000003EE coptic capital letter dei
#define  G_DJEU ( 34|T_EP2) // 0x00000402 cyrillic capital letter dje
#define  G_DZHU ( 35|T_EP2) // 0x0000040F cyrillic capital letter dzhe
#define   G_DEU ( 36|T_EP2) // 0x00000414 cyrillic capital letter de
#define  G_TSEU ( 37|T_EP2) // 0x00000426 cyrillic capital letter tse
#define  G_SHCU ( 38|T_EP2) // 0x00000429 cyrillic capital letter shcha
#define  G_KSIL ( 39|T_EP2) // 0x0000046F cyrillic small letter ksi
#define   G_UKU ( 40|T_EP2) // 0x00000478 cyrillic capital letter uk
#define   G_OTL ( 41|T_EP2) // 0x0000047F cyrillic small letter ot
#define  G_GWMU ( 42|T_EP2) // 0x00000494 cyrillic capital letter ghe with middle hook
#define   G_AHU ( 43|T_EP2) // 0x000004A8 cyrillic capital letter abkhasian ha
#define  G_INIL ( 44|T_EP2) // 0x0000056B armenian small letter ini
#define  G_XEHL ( 45|T_EP2) // 0x0000056D armenian small letter xeh
#define  G_KENL ( 46|T_EP2) // 0x0000056F armenian small letter ken
#define  G_VEWL ( 47|T_EP2) // 0x0000057E armenian small letter vew
#define  G_PIWL ( 48|T_EP2) // 0x00000583 armenian small letter piwr
#define  G_FEHL ( 49|T_EP2) // 0x00000586 armenian small letter feh
#define  G_DEVO ( 50|T_EP2) // 0x00000950 devanagari om
#define  G_DED1 ( 51|T_EP2) // 0x00000967 devanagari digit 1
#define  G_DED2 ( 52|T_EP2) // 0x00000968 devanagari digit 2
#define  G_DED3 ( 53|T_EP2) // 0x00000969 devanagari digit 3
#define  G_DED4 ( 54|T_EP2) // 0x0000096A devanagari digit 4
#define  G_DED5 ( 55|T_EP2) // 0x0000096B devanagari digit 5
#define  G_DED6 ( 56|T_EP2) // 0x0000096C devanagari digit 6
#define  G_DED7 ( 57|T_EP2) // 0x0000096D devanagari digit 7
#define  G_DED8 ( 58|T_EP2) // 0x0000096E devanagari digit 8
#define  G_DED9 ( 59|T_EP2) // 0x0000096F devanagari digit 9
#define   G_TAR ( 60|T_EP2) // 0x000010E2 georgian letter tar
#define  G_JHAN ( 61|T_EP2) // 0x000010EF georgian letter jhan
#define    G_FI ( 62|T_EP2) // 0x000010F6 georgian letter fi
#define    G_YN ( 63|T_EP2) // 0x000010F7 georgian letter yn
#define  G_ELIF ( 64|T_EP2) // 0x000010F8 georgian letter elifi
#define   G_AIN ( 65|T_EP2) // 0x000010FA georgian letter ain
#define  G_NUM2 ( 66|T_EP2) // 0x00002116 numero sign
#define   G_THI ( 67|T_EP2) // 0x00002320 top half integral
#define  G_BE8N ( 68|T_EP2) // 0x0000266B beamed 8h notes
#define  G_DWEL ( 69|T_EP2) // 0x0000A681 cyrillic small letter dwe
#define  G_DZWU ( 70|T_EP2) // 0x0000A682 cyrillic capital letter dzwe
#define  G_DZWL ( 71|T_EP2) // 0x0000A683 cyrillic small letter dzwe
#define  G_SHWU ( 72|T_EP2) // 0x0000A696 cyrillic capital letter shwe
#define   G_TZL ( 73|T_EP2) // 0x0000A729 latin small letter tz
#define  G_TELR ( 74|T_EP2) // 0x0001F4DE telephone receiver
#define  G_PERS ( 75|T_EP2) // 0x00000025 percent sign
#define  G_SECS ( 76|T_EP2) // 0x000000A7 section sign
#define  G_COPS ( 77|T_EP2) // 0x000000A9 copyright sign
#define  G_REGS ( 78|T_EP2) // 0x000000AE registered sign
#define   G_SSL ( 79|T_EP2) // 0x000000DF latin small letter sharp s
#define  G_ETHL ( 80|T_EP2) // 0x000000F0 latin small letter eth
#define  G_BETM ( 81|T_EP2) // 0x000003D0 greek beta symbol
#define  G_YATL ( 82|T_EP2) // 0x00000463 cyrillic small letter yat
#define  G_GWUU ( 83|T_EP2) // 0x00000490 cyrillic capital letter ghe with upturn
#define   G_JAL ( 84|T_EP2) // 0x00000571 armenian small letter ja
#define  G_CH2L ( 85|T_EP2) // 0x00000573 armenian small letter cheh
#define   G_BAN ( 86|T_EP2) // 0x000010D1 georgian letter ban
#define   G_ZEN ( 87|T_EP2) // 0x000010D6 georgian letter zen
#define   G_MAN ( 88|T_EP2) // 0x000010DB georgian letter man
#define   G_NAR ( 89|T_EP2) // 0x000010DC georgian letter nar
#define   G_PAR ( 90|T_EP2) // 0x000010DE georgian letter par
#define   G_RAE ( 91|T_EP2) // 0x000010E0 georgian letter rae
#define   G_SAN ( 92|T_EP2) // 0x000010E1 georgian letter san
#define  G_CHIN ( 93|T_EP2) // 0x000010E9 georgian letter chin
#define   G_HAE ( 94|T_EP2) // 0x000010F0 georgian letter hae
#define    G_HE ( 95|T_EP2) // 0x000010F1 georgian letter he
#define    G_GN ( 96|T_EP2) // 0x000010FC modifier letter georgian nar
#define  G_LARS ( 97|T_EP2) // 0x000020BE lari sign
#define  G_CARO ( 98|T_EP2) // 0x00002105 care of
#define  G_CADU ( 99|T_EP2) // 0x00002106 cada una
#define  G_LATB (100|T_EP2) // 0x000021B9 leftwards arrow to bar over rightwards arrow to bar
#define  G_RAOL (101|T_EP2) // 0x000021C4 rightwards arrow over leftwards arrow
#define    G_MO (102|T_EP2) // 0x0000A66E cyrillic letter multiocular o
#define   G_FFL (103|T_EP2) // 0x0000FB00 latin small ligature ff
#define   G_FIL (104|T_EP2) // 0x0000FB01 latin small ligature fi
#define   G_FLL (105|T_EP2) // 0x0000FB02 latin small ligature fl
#define  G_FFIL (106|T_EP2) // 0x0000FB03 latin small ligature ffi
#define  G_FFLL (107|T_EP2) // 0x0000FB04 latin small ligature ffl
#define  G_LSTL (108|T_EP2) // 0x0000FB05 latin small ligature long s t
#define  G_EMPN (109|T_EP2) // 0x0001F5C5 empty note
#define  G_NOTE (110|T_EP2) // 0x0001F5C8 note
#define  G_WAST (111|T_EP2) // 0x0001F5D1 wastebasket
#define  G_VERL (112|T_EP2) // 0x0000007C vertical line
#define  G_BROB (113|T_EP2) // 0x000000A6 broken bar
#define  G_THOL (114|T_EP2) // 0x000000FE latin small letter thorn
#define   G_IJL (115|T_EP2) // 0x00000133 latin small ligature ij
#define    G_AC (116|T_EP2) // 0x000001C2 latin letter alveolar click
#define G_LWSLU (117|T_EP2) // 0x000001C8 latin capital letter l with small letter j
#define   G_LJL (118|T_EP2) // 0x000001C9 latin small letter lj
#define G_NWSLU (119|T_EP2) // 0x000001CB latin capital letter n with small letter j
#define   G_NJL (120|T_EP2) // 0x000001CC latin small letter nj
#define  G_STIG (121|T_EP2) // 0x000003DA greek letter stigma
#define  G_KOPL (122|T_EP2) // 0x000003DF greek small letter koppa
#define  G_SAMP (123|T_EP2) // 0x000003E0 greek letter sampi
#define  G_KHEU (124|T_EP2) // 0x000003E6 coptic capital letter khei
#define  G_DJEL (125|T_EP2) // 0x00000452 cyrillic small letter dje
#define  G_KHAR (126|T_EP2) // 0x000010E5 georgian letter khar
#define  G_CHAR (127|T_EP2) // 0x000010ED georgian letter char
#define   G_HAR (128|T_EP2) // 0x000010F4 georgian letter har
#define   G_HOE (129|T_EP2) // 0x000010F5 georgian letter hoe
#define  G_DOVL (130|T_EP2) // 0x00002016 double vertical line
#define  G_DAGG (131|T_EP2) // 0x00002020 dagger
#define   G_PMS (132|T_EP2) // 0x00002030 per mille sign
#define  G_PTTS (133|T_EP2) // 0x00002031 per ten thousand sign
#define  G_BITS (134|T_EP2) // 0x000020BF bitcoin sign
#define  G_UDAW (135|T_EP2) // 0x000021A8 up down arrow with base
#define  G_DOZA (136|T_EP2) // 0x000021AF downwards zigzag arrow
#define  G_ANKH (137|T_EP2) // 0x00002625 ankh
#define  G_BLS2 (138|T_EP2) // 0x00002700 black safety scissors
#define  G_STOD (139|T_EP2) // 0x00002721 star of david
#define  G_HEMO (140|T_EP2) // 0x00002762 heavy exclamation mark ornament
#define  G_HHEM (141|T_EP2) // 0x00002763 heavy heart exclamation mark ornament
#define  G_DWEU (142|T_EP2) // 0x0000A680 cyrillic capital letter dwe
#define  G_VF1Q (143|T_EP2) // 0x000000BC vulgar fraction 1 quarter
#define  G_VF1H (144|T_EP2) // 0x000000BD vulgar fraction 1 half
#define  G_VF3Q (145|T_EP2) // 0x000000BE vulgar fraction 3 quarters
#define  G_KSIU (146|T_EP2) // 0x0000046E cyrillic capital letter ksi
#define   G_OTU (147|T_EP2) // 0x0000047E cyrillic capital letter ot
#define   G_SSU (148|T_EP2) // 0x00001E9E latin capital letter sharp s
#define  G_TRMS (149|T_EP2) // 0x00002122 trade mark sign
#define  G_VF17 (150|T_EP2) // 0x00002150 vulgar fraction 1 7th
#define  G_VF1N (151|T_EP2) // 0x00002151 vulgar fraction 1 ninth
#define  G_VF1T (152|T_EP2) // 0x00002152 vulgar fraction 1 tenth
#define  G_VF12 (153|T_EP2) // 0x00002153 vulgar fraction 1 third
#define  G_VF2T (154|T_EP2) // 0x00002154 vulgar fraction 2 thirds
#define  G_VF1F (155|T_EP2) // 0x00002155 vulgar fraction 1 fifth
#define  G_VF2F (156|T_EP2) // 0x00002156 vulgar fraction 2 fifths
#define  G_VF3F (157|T_EP2) // 0x00002157 vulgar fraction 3 fifths
#define  G_VF4F (158|T_EP2) // 0x00002158 vulgar fraction 4 fifths
#define  G_VF16 (159|T_EP2) // 0x00002159 vulgar fraction 1 6th
#define  G_VF56 (160|T_EP2) // 0x0000215A vulgar fraction 5 6ths
#define  G_VF18 (161|T_EP2) // 0x0000215B vulgar fraction 1 8h
#define  G_VF38 (162|T_EP2) // 0x0000215C vulgar fraction 3 8hs
#define  G_VF58 (163|T_EP2) // 0x0000215D vulgar fraction 5 8hs
#define  G_VF78 (164|T_EP2) // 0x0000215E vulgar fraction 7 8hs
#define  G_FRN1 (165|T_EP2) // 0x0000215F fraction numerator 1
#define  G_VF0T (166|T_EP2) // 0x00002189 vulgar fraction 0 thirds
#define  G_INTE (167|T_EP2) // 0x0000222B integral
#define  G_DOUI (168|T_EP2) // 0x0000222C double integral
#define  G_LOZE (169|T_EP2) // 0x000025CA lozenge
#define  G_SYRI (170|T_EP2) // 0x0001F489 syringe
#define  G_DESV (171|T_EP2) // 0x0000094D devanagari sign virama
#define   G_SAL (172|T_EP2) // 0x000030A1 katakana letter small a
#define   G_SIL (173|T_EP2) // 0x000030A3 katakana letter small i
#define   G_SUL (174|T_EP2) // 0x000030A5 katakana letter small u
#define   G_SEL (175|T_EP2) // 0x000030A7 katakana letter small e
#define   G_S3L (176|T_EP2) // 0x000030C3 katakana letter small tu
#define   G_SYL (177|T_EP2) // 0x000030E3 katakana letter small ya
#define   G_S4L (178|T_EP2) // 0x000030E5 katakana letter small yu
#define   G_S5L (179|T_EP2) // 0x000030E7 katakana letter small yo
#define   G_SWL (180|T_EP2) // 0x000030EE katakana letter small wa
#define   G_SKL (181|T_EP2) // 0x000030F5 katakana letter small ka
#define   G_S6L (182|T_EP2) // 0x000030F6 katakana letter small ke
#define   G_S7L (183|T_EP2) // 0x000031F2 katakana letter small su
#define    G_ED (184|T_EP2) // 0x00002014 em dash
#define   G_S8L (185|T_EP2) // 0x00003041 hiragana letter small a
#define   G_S9L (186|T_EP2) // 0x00003043 hiragana letter small i
#define   G_SBL (187|T_EP2) // 0x00003045 hiragana letter small u
#define   G_SCL (188|T_EP2) // 0x00003047 hiragana letter small e
#define   G_SDL (189|T_EP2) // 0x00003049 hiragana letter small o
#define   G_SFL (190|T_EP2) // 0x00003063 hiragana letter small tu
#define    G_N5 (191|T_EP2) // 0x0000306B hiragana letter ni
#define    G_N8 (192|T_EP2) // 0x0000306E hiragana letter no
#define   G_SGL (193|T_EP2) // 0x00003083 hiragana letter small ya
#define   G_SHL (194|T_EP2) // 0x00003085 hiragana letter small yu
#define   G_SJL (195|T_EP2) // 0x00003087 hiragana letter small yo
#define   G_SLL (196|T_EP2) // 0x0000308E hiragana letter small wa
#define     G_C (197|T_EP2) // 0x00003093 hiragana letter n
#define   G_SML (198|T_EP2) // 0x00003095 hiragana letter small ka
#define   G_SNL (199|T_EP2) // 0x00003096 hiragana letter small ke
#define     G_2 (200|T_EP2) // 0x000030A2 katakana letter a
#define     G_5 (201|T_EP2) // 0x000030A8 katakana letter e
#define   G_SOL (202|T_EP2) // 0x000030A9 katakana letter small o
#define    G_NI (203|T_EP2) // 0x000030CB katakana letter ni
#define    G_N3 (204|T_EP2) // 0x000030CC katakana letter nu
#define    G_NO (205|T_EP2) // 0x000030CE katakana letter no
#define    G_Y3 (206|T_EP2) // 0x000030E6 katakana letter yu
#define    G_YO (207|T_EP2) // 0x000030E8 katakana letter yo
#define    G_RO (208|T_EP2) // 0x000030ED katakana letter ro
#define   G_SPL (209|T_EP2) // 0x000031F3 katakana letter small to
#define   G_SQL (210|T_EP2) // 0x000031F4 katakana letter small nu
#define   G_SRL (211|T_EP2) // 0x000031F5 katakana letter small ha
#define   G_SVL (212|T_EP2) // 0x000031F6 katakana letter small hi
#define     G_U (213|T_EP2) // 0x00000909 devanagari letter u
#define    G_U2 (214|T_EP2) // 0x0000090A devanagari letter uu
#define    G_VR (215|T_EP2) // 0x0000090B devanagari letter vocalic r
#define   G_GHA (216|T_EP2) // 0x00000918 devanagari letter gha
#define   G_NGA (217|T_EP2) // 0x00000919 devanagari letter nga
#define    G_CA (218|T_EP2) // 0x0000091A devanagari letter ca
#define   G_CHA (219|T_EP2) // 0x0000091B devanagari letter cha
#define   G_JHA (220|T_EP2) // 0x0000091D devanagari letter jha
#define   G_NYA (221|T_EP2) // 0x0000091E devanagari letter nya
#define   G_TTA (222|T_EP2) // 0x0000091F devanagari letter tta
#define  G_TTHA (223|T_EP2) // 0x00000920 devanagari letter ttha
#define   G_NNA (224|T_EP2) // 0x00000923 devanagari letter nna
#define    G_TA (225|T_EP2) // 0x00000924 devanagari letter ta
#define   G_THA (226|T_EP2) // 0x00000925 devanagari letter tha
#define    G_DA (227|T_EP2) // 0x00000926 devanagari letter da
#define    G_PA (228|T_EP2) // 0x0000092A devanagari letter pa
#define    G_BA (229|T_EP2) // 0x0000092C devanagari letter ba
#define    G_MA (230|T_EP2) // 0x0000092E devanagari letter ma
#define    G_LA (231|T_EP2) // 0x00000932 devanagari letter la
#define    G_VA (232|T_EP2) // 0x00000935 devanagari letter va
#define   G_SSA (233|T_EP2) // 0x00000937 devanagari letter ssa
#define    G_SA (234|T_EP2) // 0x00000938 devanagari letter sa
#define    G_HA (235|T_EP2) // 0x00000939 devanagari letter ha
#define    G_HY (236|T_EP2) // 0x0000097A devanagari letter heavy ya
#define   G_GGA (237|T_EP2) // 0x0000097B devanagari letter gga
#define   G_JJA (238|T_EP2) // 0x0000097C devanagari letter jja
#define  G_FLOD (239|T_EP2) // 0x0001F4BE floppy disk
#define  G_SPEA (240|T_EP2) // 0x0001F508 speaker
#define  G_SW1S (241|T_EP2) // 0x0001F509 speaker with 1 sound wave
#define     G_7 (242|T_EP2) // 0x00003044 hiragana letter i
#define     G_9 (243|T_EP2) // 0x00003048 hiragana letter e
#define     G_B (244|T_EP2) // 0x0000304A hiragana letter o
#define    G_N4 (245|T_EP2) // 0x0000306A hiragana letter na
#define    G_N6 (246|T_EP2) // 0x0000306C hiragana letter nu
#define    G_N7 (247|T_EP2) // 0x0000306D hiragana letter ne
#define    G_M6 (248|T_EP2) // 0x0000307F hiragana letter mi
#define    G_M8 (249|T_EP2) // 0x00003081 hiragana letter me
#define    G_M9 (250|T_EP2) // 0x00003082 hiragana letter mo
#define    G_Y4 (251|T_EP2) // 0x00003084 hiragana letter ya
#define    G_Y5 (252|T_EP2) // 0x00003086 hiragana letter yu
#define    G_Y6 (253|T_EP2) // 0x00003088 hiragana letter yo
#define    G_R4 (254|T_EP2) // 0x00003089 hiragana letter ra
#define    G_R5 (255|T_EP2) // 0x0000308A hiragana letter ri
#define    G_R6 (256|T_EP2) // 0x0000308B hiragana letter ru
#define    G_R7 (257|T_EP2) // 0x0000308C hiragana letter re
#define    G_R8 (258|T_EP2) // 0x0000308D hiragana letter ro
#define    G_W3 (259|T_EP2) // 0x0000308F hiragana letter wa
#define    G_W4 (260|T_EP2) // 0x00003092 hiragana letter wo
#define     G_3 (261|T_EP2) // 0x000030A4 katakana letter i
#define     G_O (262|T_EP2) // 0x000030AA katakana letter o
#define    G_N2 (263|T_EP2) // 0x000030CA katakana letter na
#define    G_NE (264|T_EP2) // 0x000030CD katakana letter ne
#define    G_M2 (265|T_EP2) // 0x000030DE katakana letter ma
#define    G_MI (266|T_EP2) // 0x000030DF katakana letter mi
#define    G_M3 (267|T_EP2) // 0x000030E0 katakana letter mu
#define    G_ME (268|T_EP2) // 0x000030E1 katakana letter me
#define    G_M4 (269|T_EP2) // 0x000030E2 katakana letter mo
#define    G_Y2 (270|T_EP2) // 0x000030E4 katakana letter ya
#define    G_R2 (271|T_EP2) // 0x000030E9 katakana letter ra
#define    G_R3 (272|T_EP2) // 0x000030EB katakana letter ru
#define    G_RE (273|T_EP2) // 0x000030EC katakana letter re
#define     G_N (274|T_EP2) // 0x000030F3 katakana letter n
#define     G_I (275|T_EP2) // 0x00000907 devanagari letter i
#define    G_V2 (276|T_EP2) // 0x0000090C devanagari letter vocalic l
#define    G_V3 (277|T_EP2) // 0x00000960 devanagari letter vocalic rr
#define    G_V4 (278|T_EP2) // 0x00000961 devanagari letter vocalic ll
#define   G_ZHA (279|T_EP2) // 0x00000979 devanagari letter zha
#define  G_DDDA (280|T_EP2) // 0x0000097E devanagari letter ddda
#define   G_BBA (281|T_EP2) // 0x0000097F devanagari letter bba
#define     G_6 (282|T_EP2) // 0x00003042 hiragana letter a
#define    G_M5 (283|T_EP2) // 0x0000307E hiragana letter ma
#define    G_M7 (284|T_EP2) // 0x00003080 hiragana letter mu
#define  G_HIDY (285|T_EP2) // 0x0000309F hiragana digraph yori
#define  G_SWCS (286|T_EP2) // 0x0001F507 speaker with cancellation stroke
#define  G_SHEU (287|T_EP2) // 0x000003E2 coptic capital letter shei
#define    G_II (288|T_EP2) // 0x00000908 devanagari letter ii
#define  G_DEGC (289|T_EP2) // 0x00002103 degree celsius
#define  G_DEGF (290|T_EP2) // 0x00002109 degree fahrenheit
#define  G_SQUR (291|T_EP2) // 0x0000221A square root
#define  G_BOHI (292|T_EP2) // 0x00002321 bottom half integral
#define  G_ALIM (293|T_EP2) // 0x0001F47E alien monster
#define  G_SW3S (294|T_EP2) // 0x0001F50A speaker with 3 sound waves


#endif // GLYPHCODES
