#ifndef TERMINAL_CONSTANTS_H
#define TERMINAL_CONSTANTS_H
// This file is automatically generated, do not edit it,
// see ./prepare_fonts/README.md for more information. 

// copy these to the top of the main .ino file
// or include the generated /home/mer49/Dropbox (Cambridge University)/Personal/Hobby/Terminal/ILI9341TTY/v0.2/Uno9341TTYv16/terminal_constants.h
#define SW (320)
#define SH (240)
#define TC (53)
#define TR (20)
#define TW (TC*CW)
#define TH (TR*CH)
// Extra width 2
// Extra height 0

// Width, height, daseline, midline, topline of characters
#define CW       (6)
#define CH       (12)
#define BASELINE (2)
#define MIDLINE  (5)
#define TOPLINE  (8)

// Masks for extracting subsets of the columns of a character
#define CHARROWMASK    ((1<<CW)-1)
#define CHARLEFTMASK   (CHARROWMASK&~1)
#define CHARRIGHTMASK  (CHARROWMASK&~(1<<(CW-1)))
#define CHARMIDDLEMASK (CHARLEFTMASK&CHARRIGHTMASK)

// Row to split at to left-shift to mimic italic style
#define SPLIT          (MIDLINE+1)

// Return codes for utf-8 parsing and rendering
#define SUCCESS         (0) // Character drawn to screen
#define FAIL            (1) // Unexpected condition, likely a bug
#define NOT_MAPPED      (2) // Codepoint is not a unicode character
#define NOT_IMPLEMENTED (3) // Codepoint mapping hasn't been implemented yet
#define LOADED          (4) // Character bitmap loaded, but not yet drawn


#endif /*TERMINAL_CONSTANTS_H*/
