#!/usr/bin/env python3

# String to join multiple transforms
# (not yet implemented)
THEN = '_THEN_'

# String to interpret transform as combining/modifying previous character
COMBINING = '◌'

# Define character decompositions here
# 'unicode character' → 'base glyph' + transformation code
decompose = {
'>':'<'+HREFLECTMAG,
'\\':'/'+HREFLECTMAG,
']':'['+HREFLECTMAG,
'}':'{'+HREFLECTMAG,
')':'('+HREFLECTMAG,
'¨':' '+DIAERESIS,
'¯':' '+MACRON,
#'°':' '+RING_ABOVE,
'´':' '+ACUTE_ACCENT,
'꙾':' '+BREVE,
'¸':' '+CEDILLA,
'˜':' '+TILDE,
'͵':' '+CEDILLA,
'ͺ':' '+CEDILLA,
'ꞈ':' '+CIRCUMFLEX_ACCENT_BELOW,
'·':' '+MIDDLE_DOT_UPPER,
'¸':' '+CEDILLA,
'ˆ':' '+CIRCUMFLEX_ACCENT,
'ˇ':' '+CARON,
'ˉ':' '+MACRON,
'˘':' '+BREVE,
'˙':' '+DOT_ABOVE,
'˛':' '+OGONEK_MIDDLE,
'˜':' '+TILDE,
'˝':' '+DOUBLE_ACUTE_ACCENT,
'΄':' '+ACUTE_ACCENT,
'΅':' '+GREEK_DIALYTIKA_TONOS,
'„':' '+DOUBLE_VERTICAL_LINE_BELOW,
'Ϋ':'Y'+DIAERESIS,
'ά':'α'+ACUTE_ACCENT,
'έ':'ε'+ACUTE_ACCENT,
'ή':'η'+ACUTE_ACCENT,
'ί':'ι'+ACUTE_ACCENT,
'ϔ':'ϒ'+DIAERESIS,
'Ӫ':'Θ'+DIAERESIS,
'ϓ':'ϒ'+ACUTE_ACCENT_LEFT,
'Ά':'A'+ACUTE_ACCENT_LEFT,
'Έ':'E'+ACUTE_ACCENT_LEFT,
'Ή':'H'+ACUTE_ACCENT_LEFT,
'Ί':'I'+ACUTE_ACCENT_LEFT,
'Ό':'O'+ACUTE_ACCENT_LEFT,
'Ύ':'Y'+ACUTE_ACCENT_LEFT,
'Ώ':'Ω'+ACUTE_ACCENT_LEFT,
'ϊ':'ι'+DIAERESIS,
'ϋ':'υ'+DIAERESIS,
'ό':'o'+ACUTE_ACCENT,
'ύ':'υ'+ACUTE_ACCENT,
'ώ':'ω'+ACUTE_ACCENT,
'Ϗ':'K'+LOWER_RIGHT_TAIL,
'З́':'3'+ACUTE_ACCENT,
'Ѓ':'Γ'+ACUTE_ACCENT,
'ѓ':'г'+ACUTE_ACCENT,
'Ѝ':'И'+GRAVE_ACCENT,
'Й':'И'+BREVE,
'ѝ':'и'+GRAVE_ACCENT,
'й':'и'+BREVE,
'Ї':'I'+DIAERESIS,
'Э':'Є'+HREFLECTMAG,
'Ў':'У'+BREVE,
'Ӯ':'У'+MACRON,
'ў':'y'+BREVE,
'ӯ':'y'+MACRON,
'Ќ':'K'+ACUTE_ACCENT,
'ќ':'κ'+ACUTE_ACCENT,
'¿':'?'+VREFLECTMAG,
'À':'A'+GRAVE_ACCENT,
'Á':'A'+ACUTE_ACCENT,
'Â':'A'+CIRCUMFLEX_ACCENT,
'Ã':'A'+TILDE,
'Ä':'A'+DIAERESIS,
'Å':'A'+RING_ABOVE,
'Ç':'C'+CEDILLA,
'È':'E'+GRAVE_ACCENT,
'É':'E'+ACUTE_ACCENT,
'Ê':'E'+CIRCUMFLEX_ACCENT,
'Ë':'E'+DIAERESIS,
'Ì':'I'+GRAVE_ACCENT,
'Í':'I'+ACUTE_ACCENT,
'Î':'I'+CIRCUMFLEX_ACCENT,
'Ï':'I'+DIAERESIS,
'Ñ':'N'+TILDE,
'Ò':'O'+GRAVE_ACCENT,
'Ó':'O'+ACUTE_ACCENT,
'Ô':'O'+CIRCUMFLEX_ACCENT,
'Õ':'O'+TILDE,
'Ö':'O'+DIAERESIS,
'Ø':'O'+DIAGONAL_STROKE_UPPER,
'Ù':'U'+GRAVE_ACCENT,
'Ú':'U'+ACUTE_ACCENT,
'Û':'U'+CIRCUMFLEX_ACCENT,
'Ü':'U'+DIAERESIS,
'Ý':'Y'+ACUTE_ACCENT,
'à':'a'+GRAVE_ACCENT,
'á':'a'+ACUTE_ACCENT,
'â':'a'+CIRCUMFLEX_ACCENT,
'ã':'a'+TILDE,
'ä':'a'+DIAERESIS,
'å':'a'+RING_ABOVE,
'ç':'c'+CEDILLA,
'è':'e'+GRAVE_ACCENT,
'é':'e'+ACUTE_ACCENT,
'ê':'e'+CIRCUMFLEX_ACCENT,
'ë':'e'+DIAERESIS,
'ɘ':'e'+HREFLECTMAG,
'ì':'i'+GRAVE_ACCENT,
'í':'i'+ACUTE_ACCENT,
'î':'i'+CIRCUMFLEX_ACCENT,
'ï':'i'+DIAERESIS,
'õ':'o'+TILDE,
'ñ':'n'+TILDE,
'ò':'o'+GRAVE_ACCENT,
'ó':'o'+ACUTE_ACCENT,
'ô':'o'+CIRCUMFLEX_ACCENT,
'ö':'o'+DIAERESIS,
'ø':'o'+DIAGONAL_STROKE_LOWER,
'ù':'u'+GRAVE_ACCENT,
'ú':'u'+ACUTE_ACCENT,
'û':'u'+CIRCUMFLEX_ACCENT,
'ü':'u'+DIAERESIS,
'ý':'y'+ACUTE_ACCENT,
'ÿ':'y'+DIAERESIS,
'Ā':'A'+MACRON,
'ā':'a'+MACRON,
'Ă':'A'+BREVE,
'ă':'a'+BREVE,
'Ą':'A'+OGONEK_RIGHT,
'ą':'a'+OGONEK_RIGHT,
'Ć':'C'+ACUTE_ACCENT,
'ć':'c'+ACUTE_ACCENT,
'Ĉ':'C'+CIRCUMFLEX_ACCENT,
'ĉ':'c'+CIRCUMFLEX_ACCENT,
'Ċ':'C'+DOT_ABOVE,
'ċ':'c'+DOT_ABOVE,
'Č':'C'+CARON,
'č':'c'+CARON,
'Ď':'D'+CARON,
'ď':'d'+CARON_VARIANT,
'Đ':'D'+STROKE_MID_LEFT_HALF,
'đ':'d'+STROKE_UPPER_MID_RIGHT_HALF,
'Ē':'E'+MACRON,
'ē':'e'+MACRON,
'Ĕ':'E'+BREVE,
'ĕ':'e'+BREVE,
'Ė':'E'+DOT_ABOVE,
'ė':'e'+DOT_ABOVE,
'Ę':'E'+OGONEK_RIGHT,
'ę':'e'+OGONEK_RIGHT,
'Ě':'E'+CARON,
'ě':'e'+CARON,
'Ĝ':'G'+CIRCUMFLEX_ACCENT,
'ĝ':'g'+CIRCUMFLEX_ACCENT,
'Ğ':'G'+BREVE,
'ğ':'g'+BREVE,
'Ġ':'G'+DOT_ABOVE,
'ġ':'g'+DOT_ABOVE,
'Ģ':'G'+CEDILLA,
'ģ':'g'+CEDILLA_ABOVE_LOWER,
'Ĥ':'H'+CIRCUMFLEX_ACCENT,
'ĥ':'h'+CIRCUMFLEX_ACCENT,
'Ħ':'H'+STROKE_UPPER_FULL,
'ħ':'h'+STROKE_UPPER_LEFT_HALF, 
'Ĩ':'I'+TILDE,
'ĩ':'i'+TILDE,
'Ī':'I'+MACRON,
'ī':'i'+MACRON,
'Ĭ':'I'+BREVE,
'ĭ':'i'+BREVE,
'Į':'I'+OGONEK_MIDDLE,
'į':'i'+OGONEK_RIGHT,
'İ':'I'+DOT_ABOVE,
'Ĵ':'J'+CIRCUMFLEX_ACCENT,
'ĵ':'j'+CIRCUMFLEX_ACCENT,
'Ķ':'K'+CEDILLA,
'ķ':'k'+CEDILLA,
'Ĺ':'L'+ACUTE_ACCENT,
'ĺ':'l'+ACUTE_ACCENT,
'Ļ':'L'+CEDILLA,
'ļ':'l'+CEDILLA,
'Ľ':'L'+CARON_VARIANT,
'ľ':'l'+CARON_VARIANT,
'Ŀ':'L'+MIDDLE_DOT_UPPER,
'ŀ':'l'+MIDDLE_DOT_RIGHT,
'Ł':'L'+DIAGONAL_STROKE_LEFT,
'ł':'l'+DIAGONAL_STROKE_MID,
'Ń':'N'+ACUTE_ACCENT,
'ń':'n'+ACUTE_ACCENT,
'Ņ':'N'+CEDILLA,
'ņ':'n'+CEDILLA,
'Ň':'N'+CARON,
'ň':'n'+CARON,
'ŉ':'n'+APOSTROPHE_ABOVE_LEFT_LOWER,
'Ŋ':'N'+LOWER_RIGHT_TAIL,
'ŋ':'n'+LOWER_RIGHT_TAIL,
'Ō':'O'+MACRON,
'ō':'o'+MACRON,
'Ŏ':'O'+BREVE,
'ŏ':'o'+BREVE,
'Ő':'O'+DOUBLE_ACUTE_ACCENT,
'ő':'o'+DOUBLE_ACUTE_ACCENT,
'Ŕ':'R'+ACUTE_ACCENT,
'ŕ':'r'+ACUTE_ACCENT,
'Ŗ':'R'+CEDILLA,
'ŗ':'r'+CEDILLA,
'Ř':'R'+CARON,
'ř':'r'+CARON,
'Ś':'S'+ACUTE_ACCENT,
'ś':'s'+ACUTE_ACCENT,
'Ŝ':'S'+CIRCUMFLEX_ACCENT,
'ŝ':'s'+CIRCUMFLEX_ACCENT,
'Ş':'S'+CEDILLA,
'ş':'s'+CEDILLA,
'Š':'S'+CARON,
'š':'s'+CARON,
'Ţ':'T'+CEDILLA,
'ţ':'t'+CEDILLA,
'Ť':'T'+CARON,
'ť':'t'+CARON_VARIANT,
'Ŧ':'T'+STROKE_MID_MID_HALF,
'ŧ':'t'+STROKE_MID_LOWER_HALF,
'ө':'o'+STROKE_MID_LOWER_HALF,
'Ũ':'U'+TILDE,
'ũ':'u'+TILDE,
'Ū':'U'+MACRON,
'ū':'u'+MACRON,
'Ŭ':'U'+BREVE,
'ŭ':'u'+BREVE,
'Ů':'U'+RING_ABOVE,
'ů':'u'+RING_ABOVE,
'Ű':'U'+DOUBLE_ACUTE_ACCENT,
'ű':'u'+DOUBLE_ACUTE_ACCENT,
'Ų':'U'+OGONEK_MIDDLE,
'ų':'u'+OGONEK_RIGHT,
'Ŵ':'W'+CIRCUMFLEX_ACCENT,
'ŵ':'w'+CIRCUMFLEX_ACCENT,
'Ŷ':'Y'+CIRCUMFLEX_ACCENT,
'ŷ':'y'+CIRCUMFLEX_ACCENT,
'Ÿ':'Y'+DIAERESIS,
'Ź':'Z'+ACUTE_ACCENT,
'ź':'z'+ACUTE_ACCENT,
'Ż':'Z'+DOT_ABOVE,
'ż':'z'+DOT_ABOVE,
'Ž':'Z'+CARON,
'ž':'z'+CARON,
'∀':'A'+VREFLECTMAG,
#'Λ':'V'+VREFLECTMAG,
#'λ':'y'+VREFLECTMIN,
'¡':'!'+VREFLECTMAG,
#'ȡ':'d'+LOWER_RIGHT_CURL,
#'ȴ':'l'+LOWER_RIGHT_CURL,
#'ȵ':'n'+LOWER_RIGHT_CURL,
#'ȶ':'t'+LOWER_RIGHT_CURL,
#'Ҿ':'Ҽ'+VERTICAL_LINE_BELOW,
#'ҿ':'ҽ'+VERTICAL_LINE_BELOW,
'Ȥ':'Z'+PALATAL_HOOK,
'ȥ':'z'+PALATAL_HOOK,
'Ꞔ':'C'+PALATAL_HOOK,
'ꞔ':'c'+PALATAL_HOOK,
'ꞕ':'h'+PALATAL_HOOK,
'ƫ':'t'+PALATAL_HOOK,
'Ꙩ':'O'+MIDDLE_DOT_UPPER,
'ꙩ':'o'+MIDDLE_DOT_LOWER,
'Ͼ':'C'+MIDDLE_DOT_UPPER,
'Ͽ':'Ɔ'+MIDDLE_DOT_UPPER,
'ͼ':'c'+MIDDLE_DOT_LOWER,
'ͽ':'ͻ'+MIDDLE_DOT_LOWER,
#'Ȿ':'S'+SWASH_TAIL,
#'ȿ':'s'+SWASH_TAIL,
#'Ɀ':'7'+SWASH_TAIL,
#'Ꞡ':'G'+HIGH_OBLIQUE_STROKE,
#'ꞡ':'g'+LOW_OBLIQUE_STROKE,
#'Ꞣ':'G'+HIGH_OBLIQUE_STROKE,
#'ꞣ':'k'+LOW_OBLIQUE_STROKE,
#'Ꞥ':'N'+HIGH_OBLIQUE_STROKE,
#'ꞥ':'n'+LOW_OBLIQUE_STROKE,
#'Ꞧ':'R'+HIGH_OBLIQUE_STROKE,
#'ꞧ':'r'+LOW_OBLIQUE_STROKE,
#'Ꞩ':'S'+HIGH_OBLIQUE_STROKE,
#'ꞩ':'s'+LOW_OBLIQUE_STROKE,
'Ҙ':'3'+CEDILLA,
'ҙ':'з'+CEDILLA,
#'ꝱ':'d'+LUM,
#'ꝲ':'l'+LUM,
#'ꝳ':'m'+LUM,
#'ꝴ':'n'+LUM,
#'Ꝝ':'2'+LUM,
#'ꝶ':'я'+HREFLECTMIN+LUM,
'Ⱨ':'H'+RIGHT_DESCENDER,
'ⱨ':'h'+RIGHT_DESCENDER,
'Ⱪ':'K'+RIGHT_DESCENDER,
'ⱪ':'k'+RIGHT_DESCENDER,
'Ⱬ':'Z'+RIGHT_DESCENDER,
'ⱬ':'z'+RIGHT_DESCENDER,
'Ҳ':'X'+RIGHT_DESCENDER,
'ҳ':'x'+RIGHT_DESCENDER,
'Ҷ':'Ч'+RIGHT_DESCENDER,
'ҷ':'ч'+RIGHT_DESCENDER,
'Ң':'H'+RIGHT_DESCENDER,
'ң':'н'+RIGHT_DESCENDER,
'Қ':'K'+RIGHT_DESCENDER,
'қ':'к'+RIGHT_DESCENDER,
'Җ':'Ж'+RIGHT_DESCENDER,
'җ':'ж'+RIGHT_DESCENDER,
'Ꞑ':'N'+RIGHT_DESCENDER,
'ꞑ':'n'+RIGHT_DESCENDER,
'ↅ':'C'+RIGHT_DESCENDER,
'Ԥ':'Π'+RIGHT_DESCENDER,
'ԥ':'п'+RIGHT_DESCENDER,
'Ԧ':'Һ'+RIGHT_DESCENDER,
'ԧ':'һ'+RIGHT_DESCENDER,
'Ԯ':'Л'+RIGHT_DESCENDER,
'ԯ':'л'+RIGHT_DESCENDER,
'Ӷ':'Γ'+MIDRIGHT_DESCENDER,
'ӷ':'г'+MIDRIGHT_DESCENDER,
'Ӌ':'Ч'+MIDRIGHT_DESCENDER,
'ӌ':'ч'+MIDRIGHT_DESCENDER,
'Ҭ':'T'+MIDRIGHT_DESCENDER,
'ҭ':'т'+MIDRIGHT_DESCENDER,
#'Ҋ':'Ͷ'+LOWER_RIGHT_TAIL+BREVE,
#'ҋ':'ͷ'+LOWER_RIGHT_TAIL+BREVE,
'Ѷ':'Ѵ'+DOUBLE_GRAVE_ACCENT,
'ѷ':'ѵ'+DOUBLE_GRAVE_ACCENT,
'Ӆ':'Л'+LOWER_RIGHT_TAIL,
'ӆ':'л'+LOWER_RIGHT_TAIL,
'Ӊ':'H'+LOWER_RIGHT_TAIL,
'ӊ':'н'+LOWER_RIGHT_TAIL,
'Ӎ':'M'+LOWER_RIGHT_TAIL,
'ӎ':'м'+LOWER_RIGHT_TAIL,
'Ӄ':'K'+HOOK_2,
'ӄ':'к'+HOOK_2,
'Ӈ':'H'+HOOK_2,
'ӈ':'н'+HOOK_2,
'Ꜧ':'H'+HOOK_2,
'ꜧ':'h'+HOOK_2,
'ҁ':'c'+HOOK_2,
'Ӽ':'X'+HOOK_2,
'ӽ':'x'+HOOK_2,
'Ɱ':'M'+HOOK_2,
'ϗ':'ϰ'+HOOK_2,
'Ҟ':'K'+STROKE_UPPER_LEFT_HALF,
'ҟ':'k'+STROKE_UPPER_LEFT_HALF,
'Ꝁ':'K'+STROKE_UPPER_LEFT_HALF,
'ꝁ':'k'+STROKE_UPPER_LEFT_HALF,
'Ѣ':'Ь'+STROKE_UPPER_LEFT_HALF,
'Ҍ':'b'+STROKE_UPPER_LEFT_HALF,
#'ѣ':'ь'+STROKE_UPPER_LEFT_HALF,
#'ҍ':'ь'+STROKE_UPPER_LEFT_HALF,
'ƀ':'b'+STROKE_UPPER_LEFT_HALF,
'ħ':'h'+STROKE_UPPER_LEFT_HALF,
'Ғ':'Γ'+STROKE_UPPER_LEFT_HALF,
'Ᵽ':'P'+STROKE_UPPER_LEFT_HALF,
'Ꝉ':'L'+STROKE_UPPER_LEFT_HALF,
'ꝉ':'l'+STROKE_UPPER_LEFT_HALF,
'Ꝃ':'K'+KDIAGONAL_STROKE,
'ꝃ':'k'+KDIAGONAL_STROKE,
#'Ꝅ':'K'+STROKE_UPPER_LEFT_HALF+KDIAGONAL_STROKE,
#'ꝅ':'l'+STROKE_UPPER_LEFT_HALF+KDIAGONAL_STROKE,
'℞':'R'+KDIAGONAL_STROKE,
'Ɔ':'C'+HREFLECTMAG,
'ͻ':'c'+HREFLECTMIN,
'ꓭ':'B'+TURNMAG,
'ꓷ':'D'+HREFLECTMAG,
'Ǝ':'E'+HREFLECTMAG,
'϶':'ϵ'+HREFLECTMIN,
'з':'ε'+HREFLECTMIN, 
'ꟻ':'F'+HREFLECTMAG,
'Ⅎ':'F'+TURNMAG,
'⅁':'G'+TURNMAG,
'ꓩ':'J'+TURNMAG,
'Ʞ':'K'+TURNMAG,
'⅂':'L'+TURNMAG,
'⅃':'L'+HREFLECTMAG,
'ꟽ':'M'+VREFLECTMAG,
'ꓒ':'P'+TURNMAG,
'ꟼ':'P'+HREFLECTMAG,
'ꓤ':'R'+TURNMAG,
'Я':'R'+HREFLECTMAG,
'Ƨ':'S'+HREFLECTMAG,
'ƨ':'s'+HREFLECTMAG,
'ͻ':'c'+HREFLECTMIN,
'Ʇ':'T'+VREFLECTMAG,
'ꓵ':'U'+VREFLECTMAG,
'⅄':'Y'+VREFLECTMAG,
'Ʊ':'Ω'+VREFLECTMAG,
'ꞃ':'n'+LEFT_DESCENDER,
'ꞅ':'r'+LEFT_DESCENDER,
'ϻ':'м'+LEFT_DESCENDER,
'Ꞵ':'B'+LEFT_DESCENDER,
'Ƹ':'Ʒ'+HREFLECTMAG,
'ƹ':'ʒ'+HREFLECTMIN,
'➲':'➨'+ENTOMB,
'↊':'2'+TURNMAG,
'↋':'3'+TURNMAG,
'Ԑ':'3'+HREFLECTMAG,
'Ꝯ':'Ỽ'+VREFLECTMAG,
'ꝯ':'ỽ'+VREFLECTMIN,
'Ѽ':'Ѡ'+FERMATA,
'ѽ':'ω'+FERMATA,
'ȹ':'ȸ'+VREFLECTMIN,
'ǝ':'e'+TURNMIN,
'❮':'❬'+BOLD,
'❯':'❭'+BOLD,
'❰':'❬'+VERYBOLD,
'❱':'❭'+VERYBOLD,
'❨':'('+BOLD,
'❩':')'+BOLD,
'❪':'('+VERYBOLD,
'❫':')'+VERYBOLD,
'❴':'{'+BOLD,
'❵':'}'+BOLD,
'❲':'['+BOLD,
'❳':']'+BOLD,
'ℏ':'h'+STROKE_UPPER_LEFT_HALF,
'₸':'T'+OVERLINE,
'Ɥ':'h'+VREFLECTMAG,
'🗵':'🗴'+ENTOMB,
'🗹':'🗸'+ENTOMB,
'ꭑ':'ꭐ'+TURNMIN,
'ꬽ':'o'+VERYBOLD,
'ↆ':'𐌣'+VREFLECTMAG,
#'∇':'Δ'+VREFLECTMAG,
#'ϱ':'∂'+TURNMIN,
#'ϖ':'ω'+STROKE_MIDDLE_FULL,
#'ƃ':'b'+STROKE_MIDDLE_FULL,
'Ұ':'Y'+STROKE_MID_MID_HALF,
'Ӂ':'Ж'+BREVE,
'ӂ':'ж'+BREVE,
'Ӛ':'Ə'+DIAERESIS,
'ӛ':'ә'+DIAERESIS,
'Ӝ':'Ж'+DIAERESIS,
'ӝ':'ж'+DIAERESIS,
'Ӟ':'З'+DIAERESIS,
'ӟ':'з'+DIAERESIS,
'ӡ':'ʒ'+MACRON_BELOW,
'Ӣ':'И'+MACRON,
'ӣ':'и'+MACRON,
'Ӥ':'И'+DIAERESIS,
'ӥ':'и'+DIAERESIS,
'Ӧ':'O'+DIAERESIS,
'ӧ':'o'+DIAERESIS,
'ӫ':'ө'+DIAERESIS,
'Ӭ':'Э'+DIAERESIS,
'ӭ':'э'+DIAERESIS,
'Ӱ':'У'+DIAERESIS,
'ӱ':'y'+DIAERESIS,
'Ӳ':'У'+DOUBLE_ACUTE_ACCENT,
'ӳ':'y'+DOUBLE_ACUTE_ACCENT,
'Ӵ':'Ч'+DIAERESIS,
'ӵ':'ч'+DIAERESIS,
'Ӹ':'Ы'+DIAERESIS,
'ӹ':'ы'+DIAERESIS,
'Ƅ':'Ь'+LVERTTICK,
'ƅ':'b'+LVERTTICK,
'Ƽ':'5'+LVERTTICK,
'Ɔ':'C'+HREFLECTMAG,
'Ɓ':'B'+LEFT_HOOK_UPPER,
'Ɗ':'D'+LEFT_HOOK_UPPER,
'Ƥ':'P'+LEFT_HOOK_UPPER,
'Ƈ':'C'+RIGHT_HOOK_UPPER,
'Ɠ':'G'+RIGHT_HOOK_UPPER,
'Ƙ':'K'+RIGHT_HOOK_UPPER,
'Ⱳ':'W'+RIGHT_HOOK_UPPER,
'Ǹ':'N'+GRAVE_ACCENT,
'ǹ':'n'+GRAVE_ACCENT,
'Ǽ':'Æ'+ACUTE_ACCENT,
'ǽ':'æ'+ACUTE_ACCENT,
'Ȁ':'A'+DOUBLE_GRAVE_ACCENT,
'ȁ':'a'+DOUBLE_GRAVE_ACCENT,
'Ȃ':'A'+INVERTED_BREVE,
'ȃ':'a'+INVERTED_BREVE,
'Ȅ':'E'+DOUBLE_GRAVE_ACCENT,
'ȅ':'e'+DOUBLE_GRAVE_ACCENT,
'Ȇ':'E'+INVERTED_BREVE,
'ȇ':'e'+INVERTED_BREVE,
'Ȉ':'I'+DOUBLE_GRAVE_ACCENT,
'ȉ':'i'+DOUBLE_GRAVE_ACCENT,
'Ȋ':'I'+INVERTED_BREVE,
'ȋ':'i'+INVERTED_BREVE,
'Ȍ':'O'+DOUBLE_GRAVE_ACCENT,
'ȍ':'o'+DOUBLE_GRAVE_ACCENT,
'Ȏ':'O'+INVERTED_BREVE,
'ȏ':'o'+INVERTED_BREVE,
'Ȑ':'R'+DOUBLE_GRAVE_ACCENT,
'ȑ':'r'+DOUBLE_GRAVE_ACCENT,
'Ȓ':'R'+INVERTED_BREVE,
'ȓ':'r'+INVERTED_BREVE,
'Ȕ':'U'+DOUBLE_GRAVE_ACCENT,
'ȕ':'u'+DOUBLE_GRAVE_ACCENT,
'Ȗ':'U'+INVERTED_BREVE,
'ȗ':'u'+INVERTED_BREVE,
'Ș':'S'+COMMA_BELOW,
'ș':'s'+COMMA_BELOW,
'Ț':'T'+COMMA_BELOW,
'ț':'t'+COMMA_BELOW,
'Ȟ':'H'+CARON,
'ȟ':'h'+CARON,
'Ƞ':'n'+RIGHT_DESCENDER,
'Ȧ':'A'+DOT_ABOVE,
'ȧ':'a'+DOT_ABOVE,
'Ȩ':'E'+CEDILLA,
'ȩ':'e'+CEDILLA,
'Ȯ':'O'+DOT_ABOVE,
'ȯ':'o'+DOT_ABOVE,
'Ȳ':'Y'+MACRON,
'ȳ':'y'+MACRON,
'Ӑ':'A'+BREVE,
'ӑ':'a'+BREVE,
'Ḃ':'B'+DOT_ABOVE,
'ḃ':'b'+DOT_ABOVE,
'Ḋ':'D'+DOT_ABOVE,
'ḋ':'d'+DOT_ABOVE,
'Ḟ':'F'+DOT_ABOVE,
'ḟ':'f'+DOT_ABOVE,
'Ṁ':'M'+DOT_ABOVE,
'ṁ':'m'+DOT_ABOVE,
'Ṗ':'P'+DOT_ABOVE,
'ṗ':'p'+DOT_ABOVE,
'Ṡ':'S'+DOT_ABOVE,
'ṡ':'s'+DOT_ABOVE,
'Ṫ':'T'+DOT_ABOVE,
'ṫ':'t'+DOT_ABOVE,
'Ẁ':'W'+GRAVE_ACCENT,
'ẁ':'w'+GRAVE_ACCENT,
'Ẃ':'W'+ACUTE_ACCENT,
'ẃ':'w'+ACUTE_ACCENT,
'Ẅ':'W'+DIAERESIS,
'ẅ':'w'+DIAERESIS,
'Ỳ':'Y'+GRAVE_ACCENT,
'ỳ':'y'+GRAVE_ACCENT,
'Ⱥ':'A'+DIAGONAL_STROKE_UPPER,
'Ȼ':'C'+DIAGONAL_STROKE_UPPER,
'ȼ':'c'+DIAGONAL_STROKE_LOWER,
'Ƚ':'L'+STROKE_UPPER_LEFT_HALF,
'Ⱦ':'T'+DIAGONAL_STROKE_UPPER,
'Ʉ':'U'+STROKE_UPPER_FULL,
'Ɇ':'E'+DIAGONAL_STROKE_UPPER,
'ɇ':'e'+DIAGONAL_STROKE_LOWER,
'Ɉ':'J'+STROKE_MID_MID_HALF,
'ɉ':'j'+STROKE_MID_LOWER_HALF,
'Ɏ':'Y'+STROKE_UPPER_FULL,
'ɏ':'y'+STROKE_MIDDLE_FULL,
'Ǎ':'A'+CARON,
'ǎ':'a'+CARON,
'Ǐ':'I'+CARON,
'ǐ':'i'+CARON,
'Ǒ':'O'+CARON,
'ǒ':'o'+CARON,
'Ǔ':'U'+CARON,
'ǔ':'u'+CARON,
'Ǧ':'G'+CARON,
'ǧ':'g'+CARON,
'Ǩ':'K'+CARON,
'ǩ':'k'+CARON,
'ǰ':'j'+CARON,
'Ǵ':'G'+ACUTE_ACCENT,
'ǵ':'ǵ'+ACUTE_ACCENT,
'Ǯ':'Ʒ'+ACUTE_ACCENT,
'ǯ':'ʒ'+ACUTE_ACCENT,
'Ǆ':'Ǳ'+CARON,
'ǅ':'ǲ'+CARON,
'ǆ':'ǳ'+CARON,
'Ǣ':'Æ'+MACRON,
'ǣ':'æ'+MACRON,
'Ǫ':'O'+OGONEK_MIDDLE,
'ǫ':'o'+OGONEK_MIDDLE,
'Ƌ':'Б'+HREFLECTMAG,
'ƍ':'δ'+VREFLECTMIN,
'Ƶ':'Z'+STROKE_MID_MID_HALF,
'ƶ':'z'+STROKE_MID_LOWER_HALF,
'ƻ':'2'+STROKE_MID_MID_HALF,
'Ɍ':'R'+STROKE_MID_MID_HALF,
'ɍ':'R'+STROKE_MID_LOWER_HALF,
'Ɨ':'I'+STROKE_MID_MID_HALF,
'ƚ':'l'+STROKE_MID_MID_HALF,
'ɨ':'i'+STROKE_MID_LOWER_HALF,
'ɟ':'ȷ'+STROKE_MID_LOWER_HALF,
'ɒ':'ɑ'+HREFLECTMAG,
'ℊ':'g'+ITALIC,
'Ϭ':'Ỽ'+HREFLECTMAG,
'ϭ':'ỽ'+HREFLECTMAG,
'❶':'1'+ENTOMB,
'❷':'2'+ENTOMB,
'❸':'3'+ENTOMB,
'❹':'4'+ENTOMB,
'❺':'5'+ENTOMB,
'❻':'6'+ENTOMB,
'❼':'7'+ENTOMB,
'❽':'8'+ENTOMB,
'❾':'9'+ENTOMB,
'➀':'1'+ENTOMB,
'➁':'2'+ENTOMB,
'➂':'3'+ENTOMB,
'➃':'4'+ENTOMB,
'➄':'5'+ENTOMB,
'➅':'6'+ENTOMB,
'➆':'7'+ENTOMB,
'➇':'8'+ENTOMB,
'➈':'9'+ENTOMB,
'➊':'1'+ENTOMB,
'➋':'2'+ENTOMB,
'➌':'3'+ENTOMB,
'➍':'4'+ENTOMB,
'➎':'5'+ENTOMB,
'➏':'6'+ENTOMB,
'➐':'7'+ENTOMB,
'➑':'8'+ENTOMB,
'➒':'9'+ENTOMB,
'⓫':'⒒'+ENTOMB,
'⓬':'⒓'+ENTOMB,
'⓭':'⒔'+ENTOMB,
'⓮':'⒕'+ENTOMB,
'⓯':'⒖'+ENTOMB,
'⓰':'⒗'+ENTOMB,
'⓱':'⒘'+ENTOMB,
'⓲':'⒙'+ENTOMB,
'⓳':'⒚'+ENTOMB,
'⓴':'⒛'+ENTOMB,
'❿':'⒑'+ENTOMB, 
'🖣':'🖢'+VREFLECTMAG,
'🖚':'🖛'+HREFLECTMAG,
'🖓':'🖒'+VREFLECTMAG,
'◄':'►'+HREFLECTMAG,
'▼':'▲'+VREFLECTMAG,
'🔼':'▲'+ENTOMB, 
'🔽':'▼'+ENTOMB, 
'⌐':'¬'+HREFLECTMIN,
'ΰ':'υ'+GREEK_DIALYTIKA_TONOS,
'ΐ':'ι'+GREEK_DIALYTIKA_TONOS,
'♤':'♠'+OUTLINE,
'♡':'♥'+OUTLINE,
'♧':'♣'+OUTLINE,
'♢':'♦'+OUTLINE,
'✘':'✗'+BOLD,
'✔':'✓'+BOLD,
'☒':'✕'+ENTOMB,
'☑':'✓'+ENTOMB,
'𝜮':'Σ'+ITALIC,
'𝝨':'Σ'+BOLD,
'𝞢':'Σ'+BOLDITALIC,
'⅀':'Σ'+OUTLINE,
'↲':'↰'+VREFLECTMAG,
'↱':'↰'+HREFLECTMAG,
'↳':'↰'+TURNMAG,
'↷':'↶'+HREFLECTMAG,
'↻':'↺'+HREFLECTMAG,
'⁋':'¶'+HREFLECTMAG,
'↗':'↖'+HREFLECTMAG,
'↘':'↖'+TURNMAG,
'↙':'↖'+VREFLECTMAG,
'Ḅ':'B'+DOT_BELOW,
'ḅ':'b'+DOT_BELOW,
'Ḇ':'B'+LINE_BELOW,
'ḇ':'b'+LINE_BELOW,
'Ḍ':'D'+DOT_BELOW,
'ḍ':'d'+DOT_BELOW,
'Ḏ':'D'+LINE_BELOW,
'ḏ':'d'+LINE_BELOW,
'Ḑ':'D'+CEDILLA,
'ḑ':'d'+CEDILLA,
'Ḓ':'D'+CIRCUMFLEX_ACCENT_BELOW,
'ḓ':'d'+CIRCUMFLEX_ACCENT_BELOW,
'Ḙ':'E'+CIRCUMFLEX_ACCENT_BELOW,
'ḙ':'e'+CIRCUMFLEX_ACCENT_BELOW,
'Ḛ':'E'+TILDE_BELOW,
'ḛ':'e'+TILDE_BELOW,
'Ḡ':'G'+MACRON,
'ḡ':'g'+MACRON,
'Ḣ':'H'+DOT_ABOVE,
'ḣ':'h'+DOT_ABOVE,
'Ḥ':'H'+DOT_BELOW,
'ḥ':'h'+DOT_BELOW,
'Ḧ':'H'+DIAERESIS,
'ḧ':'h'+DIAERESIS,
'Ḩ':'H'+CEDILLA,
'ḩ':'h'+CEDILLA,
'Ḫ':'H'+BREVE_BELOW,
'ḫ':'h'+BREVE_BELOW,
'Ḭ':'I'+TILDE_BELOW,
'ḭ':'i'+TILDE_BELOW,
'Ḱ':'K'+ACUTE_ACCENT,
'ḱ':'k'+ACUTE_ACCENT,
'Ḳ':'K'+DOT_BELOW,
'ḳ':'k'+DOT_BELOW,
'Ḵ':'K'+LINE_BELOW,
'ḵ':'k'+LINE_BELOW,
'Ḷ':'L'+DOT_BELOW,
'ḷ':'l'+DOT_BELOW,
'Ḻ':'L'+LINE_BELOW,
'ḻ':'l'+LINE_BELOW,
'Ḽ':'L'+CIRCUMFLEX_ACCENT_BELOW,
'ḽ':'l'+CIRCUMFLEX_ACCENT_BELOW,
'Ḿ':'M'+ACUTE_ACCENT,
'ḿ':'m'+ACUTE_ACCENT,
'Ṃ':'M'+DOT_BELOW,
'ṃ':'m'+DOT_BELOW,
'Ṅ':'N'+DOT_ABOVE,
'ṅ':'n'+DOT_ABOVE,
'Ṇ':'N'+DOT_BELOW,
'ṇ':'n'+DOT_BELOW,
'Ṉ':'N'+LINE_BELOW,
'ṉ':'n'+LINE_BELOW,
'Ṋ':'N'+CIRCUMFLEX_ACCENT_BELOW,
'ṋ':'n'+CIRCUMFLEX_ACCENT_BELOW,
'Ṕ':'P'+ACUTE_ACCENT,
'ṕ':'p'+ACUTE_ACCENT,
'Ṙ':'R'+DOT_ABOVE,
'ṙ':'r'+DOT_ABOVE,
'Ṛ':'R'+DOT_BELOW,
'ṛ':'r'+DOT_BELOW,
'Ṟ':'R'+LINE_BELOW,
'ṟ':'r'+LINE_BELOW,
'Ṣ':'S'+DOT_BELOW,
'ṣ':'s'+DOT_BELOW,
'Ṭ':'T'+DOT_BELOW,
'ṭ':'t'+DOT_BELOW,
'Ṯ':'T'+LINE_BELOW,
'ṯ':'t'+LINE_BELOW,
'Ṱ':'T'+CIRCUMFLEX_ACCENT_BELOW,
'ṱ':'t'+CIRCUMFLEX_ACCENT_BELOW,
'Ṳ':'U'+DIAERESIS_BELOW,
'ṳ':'u'+DIAERESIS_BELOW,
'Ṵ':'U'+TILDE_BELOW,
'ṵ':'u'+TILDE_BELOW,
'Ṷ':'U'+CIRCUMFLEX_ACCENT_BELOW,
'ṷ':'u'+CIRCUMFLEX_ACCENT_BELOW,
'Ṽ':'V'+TILDE,
'ṽ':'v'+TILDE,
'Ṿ':'V'+DOT_BELOW,
'ṿ':'v'+DOT_BELOW,
'Ẇ':'W'+DOT_ABOVE,
'ẇ':'w'+DOT_ABOVE,
'Ẉ':'W'+DOT_BELOW,
'ẉ':'w'+DOT_BELOW,
'Ẋ':'X'+DOT_ABOVE,
'ẋ':'x'+DOT_ABOVE,
'Ẍ':'X'+DIAERESIS,
'ẍ':'x'+DIAERESIS,
'Ẏ':'Y'+DOT_ABOVE,
'ẏ':'y'+DOT_ABOVE,
'Ẑ':'Z'+CIRCUMFLEX_ACCENT,
'ẑ':'z'+CIRCUMFLEX_ACCENT,
'Ẓ':'Z'+DOT_BELOW,
'ẓ':'z'+DOT_BELOW,
'Ẕ':'Z'+LINE_BELOW,
'ẕ':'z'+LINE_BELOW,
'ẖ':'h'+LINE_BELOW,
'ẗ':'t'+DIAERESIS,
'ẘ':'w'+RING_ABOVE,
'ẙ':'y'+RING_ABOVE,
'ẚ':'a'+RIGHT_HALF_RING_ABOVE,
'ẛ':'s'+DOT_ABOVE,
'ẜ':'ſ'+DIAGONAL_STROKE_MID,
#'ẝ':'s'+HIGH_STROKE_UPPER,
'Ạ':'A'+DOT_BELOW,
'ạ':'a'+DOT_BELOW,
'Ả':'A'+HOOK_ABOVE,
'ả':'a'+HOOK_ABOVE,
'Ẹ':'E'+DOT_BELOW,
'ẹ':'e'+DOT_BELOW,
'Ẻ':'E'+HOOK_ABOVE,
'ẻ':'e'+HOOK_ABOVE,
'Ẽ':'E'+TILDE,
'ẽ':'e'+TILDE,
'Ỉ':'I'+HOOK_ABOVE,
'ỉ':'i'+HOOK_ABOVE,
'Ị':'I'+DOT_BELOW,
'ị':'i'+DOT_BELOW,
'Ọ':'O'+DOT_BELOW,
'ọ':'o'+DOT_BELOW,
'Ỏ':'O'+HOOK_ABOVE,
'ỏ':'o'+HOOK_ABOVE,
'Ụ':'U'+DOT_BELOW,
'ụ':'u'+DOT_BELOW,
'Ủ':'U'+HOOK_ABOVE,
'ủ':'u'+HOOK_ABOVE,
'Ỵ':'Y'+DOT_BELOW,
'ỵ':'y'+DOT_BELOW,
'Ỷ':'Y'+HOOK_ABOVE,
'ỷ':'y'+HOOK_ABOVE,
'Ỹ':'Y'+TILDE,
'ỹ':'y'+TILDE,
#'Ỿ':'Y'+LOOP,
'◁':'◀'+OUTLINE,
'▷':'▶'+OUTLINE,
'≤':'≥'+HREFLECTMAG,
'∓':'±'+VREFLECTMAG,
'»':'«'+HREFLECTMAG,
'⍶':'α'+LINE_BELOW,
'⍷':'ε'+LINE_BELOW,
'⍸':'ι'+LINE_BELOW,
'⍹':'ω'+LINE_BELOW,
'❙':'❘'+BOLD,
#'❚':'❘'+VERYBOLD,
'🔙':'←'+ENTOMB,
'🔚':'←'+ENTOMB,
'🔛':'↔'+ENTOMB,
'🔜':'→'+ENTOMB,
'🔝':'↑'+ENTOMB,
'💲':'$'+ENTOMB,
'🗶':'✗'+BOLD,
'☺':'☻'+OUTLINE,
'⬅':'←' + BOLD,
'➡':'→' + BOLD,
#'⮕':'→' + VERYBOLD,
'←':'→' + HREFLECTMAG,
'↓':'↑' + VREFLECTMAG,
'⬆':'↑' + BOLD,
'⬇':'↓' + BOLD,
'⇦':'←' + OUTLINE,
'⇨':'→' + OUTLINE,
'⇧':'↑' + OUTLINE,
'⇩':'↓' + OUTLINE,
'⬄':'↔' + OUTLINE,
'⇳':'↕' + OUTLINE,
'⬌':'↔' + BOLD,
'⬍':'↕' + BOLD,
'⬉':'↖' + BOLD,
'⬈':'↗' + BOLD,
'⬊':'↘' + BOLD,
'⬋':'↙' + BOLD,
'⬁':'↖' + OUTLINE,
'⬀':'↗' + OUTLINE,
'⬂':'↘' + OUTLINE,
'⬃':'↙' + OUTLINE,
'🡀':'🡂'+HREFLECTMAG,
'🠼':'🠾'+HREFLECTMAG,
'🡃':'🡁'+VREFLECTMAG,
'🠸':'🠺'+HREFLECTMAG,
'🠻':'🠹'+VREFLECTMAG,
'🡄':'🡆'+HREFLECTMIN,
'🡇':'🡅'+VREFLECTMAG,
'🠔':'🠖'+HREFLECTMAG,
'🠗':'🠕'+VREFLECTMAG,
#'🠐':'🠔'+FAINT,
#'🠒':'🠖'+FAINT,
#'🠑':'🠕'+FAINT,
#'🠓':'🠗'+FAINT,
'🠘':'🠔'+BOLD,
'🠚':'🠖'+BOLD,
'🠙' :'🠕'+BOLD,
'🠛':'🠗'+BOLD,
'🠜':'🠔'+VERYBOLD,
'🠞':'🠖'+VERYBOLD,
'🠝':'🠕'+VERYBOLD,
'🠟':'🠗'+VERYBOLD,
#'🡠':'🡨'+FAINT,
#'🡢':'🡪'+FAINT,
#'🡡':'🡩'+FAINT,
#'🡣':'🡫'+FAINT,
#'🡤':'🡬'+FAINT,
#'🡥':'🡭'+FAINT,
#'🡦':'🡮'+FAINT,
#'🡧':'🡯'+FAINT,
'🡰':'🡨'+BOLD,
'🡲':'🡪'+BOLD,
'🡱':'🡩'+BOLD,
'🡳':'🡫'+BOLD,
'🡴':'🡬'+BOLD,
'🡵':'🡭'+BOLD,
'🡶':'🡮'+BOLD,
'🡷':'🡯'+BOLD,
'🡸':'🡨'+VERYBOLD,
'🡺':'🡪'+VERYBOLD,
'🡹':'🡩'+VERYBOLD,
'🡻':'🡫'+VERYBOLD,
'🡼':'🡬'+VERYBOLD,
'🡽':'🡭'+VERYBOLD,
'🡾':'🡮'+VERYBOLD,
'🡿':'🡯'+VERYBOLD,
'🡭':'🡮'+VREFLECTMAG,
'🡬':'🡮'+TURNMAG,
'🡯':'🡮'+HREFLECTMAG,
'⮊':'🠖'+ENTOMB,
'⮈':'🠔'+ENTOMB,
'⮉':'🠕'+ENTOMB,
'⮋':'🠕'+ENTOMB,
'⮜':'⮞'+HREFLECTMAG,
'⮟':'⮝'+VREFLECTMAG,
'⇠':'⇢'+HREFLECTMAG,
'⇣':'⇡'+VREFLECTMAG,
'↾':'↿'+HREFLECTMAG,
'⇃':'↿'+VREFLECTMAG,
'⇂':'↿'+TURNMAG,
'↼':'⇀'+HREFLECTMAG,
'↽':'⇀'+TURNMAG,
'⇁':'⇀'+VREFLECTMAG,
'⥌':'⥍'+HREFLECTMAG,
'⥊':'⥋'+VREFLECTMAG,
'⯬':'⯮'+HREFLECTMIN,
'⯭':'⯯'+VREFLECTMAG,
'⇐':'⇒'+HREFLECTMIN,
'↞':'↠'+HREFLECTMIN,
'↟':'↡'+VREFLECTMAG,
'↗':'↖'+HREFLECTMAG,
'↘':'↖'+TURNMAG,
'↙':'↖'+VREFLECTMAG,
'⥀':'⥁'+HREFLECTMAG,
'ʁ':'ʀ'+VREFLECTMIN,
'が':'か'+VOICED_SOUND_MARK,
'ぎ':'き'+VOICED_SOUND_MARK,
'ぐ':'く'+VOICED_SOUND_MARK,
'げ':'け'+VOICED_SOUND_MARK,
'ご':'こ'+VOICED_SOUND_MARK,
'ざ':'さ'+VOICED_SOUND_MARK,
'じ':'し'+VOICED_SOUND_MARK,
'ず':'す'+VOICED_SOUND_MARK,
'ぜ':'せ'+VOICED_SOUND_MARK,
'ぞ':'そ'+VOICED_SOUND_MARK,
'だ':'た'+VOICED_SOUND_MARK,
'ぢ':'ち'+VOICED_SOUND_MARK,
'づ':'つ'+VOICED_SOUND_MARK,
'で':'て'+VOICED_SOUND_MARK,
'ど':'と'+VOICED_SOUND_MARK,
'ば':'は'+VOICED_SOUND_MARK,
'ぱ':'は'+SEMIVOICED_SOUND_MARK,
'び':'ひ'+VOICED_SOUND_MARK,
'ぴ':'ひ'+SEMIVOICED_SOUND_MARK,
'ぶ':'ふ'+VOICED_SOUND_MARK,
'ぷ':'ふ'+SEMIVOICED_SOUND_MARK,
'べ':'へ'+VOICED_SOUND_MARK,
'ぺ':'へ'+SEMIVOICED_SOUND_MARK,
'ぼ':'ほ'+VOICED_SOUND_MARK,
'ぽ':'ほ'+SEMIVOICED_SOUND_MARK,
'ゔ':'う'+VOICED_SOUND_MARK,
'ヷ':'ワ'+VOICED_SOUND_MARK,
'ヸ':'ヰ'+VOICED_SOUND_MARK,
'ヹ':'ヱ'+VOICED_SOUND_MARK,
'ヺ':'ヲ'+VOICED_SOUND_MARK,
'ヾ':'ヽ'+VOICED_SOUND_MARK,
'ヴ':'ウ'+VOICED_SOUND_MARK,
'ボ':'ホ'+VOICED_SOUND_MARK,
'ポ':'ホ'+SEMIVOICED_SOUND_MARK,
'ベ':'ヘ'+VOICED_SOUND_MARK,
'ペ':'ヘ'+SEMIVOICED_SOUND_MARK,
'ブ':'フ'+VOICED_SOUND_MARK,
'プ':'フ'+SEMIVOICED_SOUND_MARK,
'ビ':'ヒ'+VOICED_SOUND_MARK,
'ピ':'ヒ'+SEMIVOICED_SOUND_MARK,
'バ':'ハ'+VOICED_SOUND_MARK,
'パ':'ハ'+SEMIVOICED_SOUND_MARK,
'ド':'ト'+VOICED_SOUND_MARK,
'デ':'テ'+VOICED_SOUND_MARK,
'ヅ':'ツ'+VOICED_SOUND_MARK,
'ヂ':'チ'+VOICED_SOUND_MARK,
'ダ':'タ'+VOICED_SOUND_MARK,
'ゾ':'ソ'+VOICED_SOUND_MARK,
'ゼ':'セ'+VOICED_SOUND_MARK,
'ズ':'ス'+VOICED_SOUND_MARK,
'ジ':'シ'+VOICED_SOUND_MARK,
'ザ':'サ'+VOICED_SOUND_MARK,
'ゴ':'コ'+VOICED_SOUND_MARK,
'ゲ':'ケ'+VOICED_SOUND_MARK,
'グ':'ク'+VOICED_SOUND_MARK,
'ゞ':'ゝ'+VOICED_SOUND_MARK,
'ギ':'キ'+SEMIVOICED_SOUND_MARK,
'ガ':'カ'+SEMIVOICED_SOUND_MARK,
'ヿ':'L'+TURNMIN,
'\u3099':COMBINING+VOICED_SOUND_MARK,
'\u309A':COMBINING+SEMIVOICED_SOUND_MARK,
'゛':' '+VOICED_SOUND_MARK,
'゜':' '+SEMIVOICED_SOUND_MARK,
'Ե':'Բ'+VREFLECTMAG,
'Ժ':'Գ'+VREFLECTMAG,
'Ն':'Ղ'+TURNMAG,
'Ր':'J'+TURNMAG,
'ՙ':' '+LEFT_HALF_RING_ABOVE,
'՛':COMBINING+EMPHASIS_MARK,
'՜':COMBINING+EXCLAMATION_MARK,
'՞':COMBINING+QUESTION_MARK,
'ա':'m'+VREFLECTMIN,
'ւ':'г'+VREFLECTMIN,
'ֈ':'յ'+STROKE_MID_LOWER_HALF,
'⊙':'○'+MIDDLE_DOT_UPPER,
'წ':'შ'+HREFLECTMAG,
'ხ':'ძ'+HREFLECTMAG,
'ॱ':' '+DOT_ABOVE,
'\u0900':COMBINING+DEVANAGARI_INVERTED_CANDRABINDU,
'\u0901':COMBINING+DEVANAGARI_CANDRABINDU,
'\u0902':COMBINING+DEVANAGARI_ANUSVARA,
'\u093A':COMBINING+DEVANAGARI_OE,
'\u093C':COMBINING+DEVANAGARI_NUKTA,
'\u0941':COMBINING+DEVANAGARI_U,
'\u0942':COMBINING+DEVANAGARI_UU,
'\u0943':COMBINING+DEVANAGARI_VOCALIC_R,
'\u0944':COMBINING+DEVANAGARI_VOCALIC_RR,
'\u0945':COMBINING+DEVANAGARI_CANDRA_E,
'\u0946':COMBINING+DEVANAGARI_SHORT_E,
'\u0947':COMBINING+DEVANAGARI_E,
'\u0948':COMBINING+DEVANAGARI_AI,
'\u0951':COMBINING+DEVANAGARI_UDATTA,
'\u0952':COMBINING+DEVANAGARI_ANUDATTA,
'\u0953':COMBINING+DEVANAGARI_GRAVE,
'\u0954':COMBINING+DEVANAGARI_ACUTE,
'\u0955':COMBINING+DEVANAGARI_VOWEL_CANDRA_LONG_E,
'\u0956':COMBINING+DEVANAGARI_UE,
'\u0957':COMBINING+DEVANAGARI_UUE,
'\u0962':COMBINING+DEVANAGARI_VOCALIC_L,
'\u0953':COMBINING+DEVANAGARI_VOCALIC_LL,
'ऄ':'अ'+DEVANAGARI_SHORT_E,
'ऍ':'ए'+DEVANAGARI_CANDRA_E,
'ऎ':'ए'+DEVANAGARI_SHORT_E,
'ऐ':'ए'+DEVANAGARI_E,
'ऑ':'आ'+DEVANAGARI_CANDRA_E,
'ऒ':'आ'+DEVANAGARI_SHORT_E,
'ओ':'आ'+DEVANAGARI_E,
'औ':'आ'+DEVANAGARI_AI,
'ऩ':'न'+DEVANAGARI_NUKTA,
'ऱ':'र'+DEVANAGARI_NUKTA,
'ऴ':'ळ'+DEVANAGARI_NUKTA,
'क़':'क'+DEVANAGARI_NUKTA,
'ख़':'ख'+DEVANAGARI_NUKTA,
'ग़':'ग'+DEVANAGARI_NUKTA,
'ज़':'ज'+DEVANAGARI_NUKTA,
'ड़':'ड'+DEVANAGARI_NUKTA,
'ढ़':'ढ'+DEVANAGARI_NUKTA,
'फ़':'फ'+DEVANAGARI_NUKTA,
'य़':'य'+DEVANAGARI_NUKTA,
## These are missing at the moment
#'\u093E':COMBINING+'\u093E',
'\u093B':'\u093E'+DEVANAGARI_OE,
'\u0949':'\u093E'+DEVANAGARI_CANDRA_E,
'\u094A':'\u093E'+DEVANAGARI_SHORT_E,
'\u094B':'\u093E'+DEVANAGARI_E,
'\u094C':'\u093E'+DEVANAGARI_AI,
}



"""
What to do about these? 
0x903  ः DEVANAGARI SIGN VISARGA
0x93B  ऻ DEVANAGARI VOWEL SIGN OOE
0x93E  ा DEVANAGARI VOWEL SIGN AA
0x93F  ि DEVANAGARI VOWEL SIGN I
0x940  ी DEVANAGARI VOWEL SIGN II
0x949  ॉ DEVANAGARI VOWEL SIGN CANDRA O
0x94A  ॊ DEVANAGARI VOWEL SIGN SHORT O
0x94B  ो DEVANAGARI VOWEL SIGN O
0x94C  ौ DEVANAGARI VOWEL SIGN AU
0x94E  ॎ DEVANAGARI VOWEL SIGN PRISHTHAMATRA E
0x94F  ॏ DEVANAGARI VOWEL SIGN AW
"""

#🡆🡅🠹🠺🡂🠽🡮⮞⮝⇡⇢↿⇀⥍⥋⇒↠↡
#↖↺⇄↹↯↰↴↶
#⥎⥐⥑⥏⥒⥓⥖⥗⥔⥕⥘⥙⥚⥛⥞⥟⥜⥝⥠⥡
#⥢⥤⥣⥥⇋⇌⥦⥨⥧⥩⥪⥬⥫⥭⥮⥯
#⮄⮆⮅⮇⇈⇊⇇⇉⇆⇄⇅⇵⮀⮂⮁⮃⭾⭿
#⇑⇓⇕⇖⇗⇘⇙⇍⇏⇎⤂⤃⤄⤆⤇⬱⇶⇚⇛⤊⤋⭅⭆⟰⟱
#⭰⭲⭱⭳⭶⭷⭸⭹⇤⇥⤒⤓↨⤝⤞⤟⤠↤↦↥↧⬶⤅⟻⟼↸⇱⇲
#⇜⇝⬳⟿↜↝↭⬿⤳
#⇷⇸⤉⤈⇹⇺⇻⇞⇟⇼⭺⭼⭻⭽⬴⤀⬵⤁⬹⤔⬺⤕⬻⤖⬼⤗⬽⤘
#⮠↲↵⮐↩⤶⮡↳⮑↪⤷⮢↰⮣⮤⬑⮥⬏⮦⬐⮧↴⬎↱⮒⮓
#⤣⤤⤥⤦⭚⭛↫↬
#⤙⤚⤛⤜⥼⥽⥾⥿
#⭜⭝⭞⭟↯⭍⇿
#↶↷⤾⤿⤺⤻⤹⤸⭯⭮↺↻⟲⟳⥁🗘⮎⮌⮏⮍⮔⤴⤵
#⮰⮱⮲⮳⮴⮵⮶⮷➥➦⮨⮩⮪⮫⮬⮭⮮⮯
#➩➪➫➬➭➮➯➱🢠🢡🢢🢣🢤🢥🢦🢧🢨🢩🢪🢫
#⇪⮸⇫⇬⇭⇮⇯➳➵➴➶➸➷➹➙➘➚➾⇰➟➠➧➨➺➻➼➽
#🠴🠶🠵🠷🢘🢚🢙🢛🔙🔚🔛🔜🔝🔁🔂🔃🔄↢↣⭎⭏⥂⥃⥄⥉⥰
#⤪⤨⤧⤩⤭⤮⤱⤲⤯⤰⤫⤬
#⇔⟺
#►▲⭤⭥⭦⭧⭨⭩
#⤡⤢
#↚↛↮ 

'''
Notes: 
Script used to auto-generate some of these

s = 'Ḅ ḅ Ḇ ḇ Ḉ ḉ Ḍ ḍ Ḏ ḏ Ḑ ḑ Ḓ ḓ Ḕ ḕ Ḗ ḗ Ḙ ḙ Ḛ ḛ Ḝ ḝ Ḡ ḡ Ḣ ḣ Ḥ ḥ Ḧ ḧ Ḩ ḩ Ḫ ḫ Ḭ ḭ Ḯ ḯ Ḱ ḱ Ḳ ḳ Ḵ ḵ Ḷ ḷ Ḹ ḹ Ḻ ḻ Ḽ ḽ Ḿ ḿ Ṃ ṃ Ṅ ṅ Ṇ ṇ Ṉ ṉ Ṋ ṋ Ṍ ṍ Ṏ ṏ Ṑ ṑ Ṓ ṓ Ṕ ṕ Ṙ ṙ Ṛ ṛ Ṝ ṝ Ṟ ṟ Ṣ ṣ Ṥ ṥ Ṧ ṧ Ṩ ṩ Ṭ ṭ Ṯ ṯ Ṱ ṱ Ṳ ṳ Ṵ ṵ Ṷ ṷ Ṹ ṹ Ṻ ṻ Ṽ ṽ Ṿ ṿ Ẇ ẇ Ẉ ẉ Ẋ ẋ Ẍ ẍ Ẏ ẏ Ẑ ẑ Ẓ ẓ Ẕ ẕ ẖ ẗ ẘ ẙ ẚ ẛ ẜ ẝ Ạ ạ Ả ả Ấ ấ Ầ ầ Ẩ ẩ Ẫ ẫ Ậ ậ Ắ ắ Ằ ằ Ẳ ẳ Ẵ ẵ Ặ ặ Ẹ ẹ Ẻ ẻ Ẽ ẽ Ế ế Ề ề Ể ể Ễ ễ Ệ ệ Ỉ ỉ Ị ị Ọ ọ Ỏ ỏ Ố ố Ồ ồ Ổ ổ Ỗ ỗ Ộ ộ Ớ ớ Ờ ờ Ở ở Ỡ ỡ Ợ ợ Ụ ụ Ủ ủ Ứ ứ Ừ ừ Ử ử Ữ ữ Ự ự Ỵ ỵ Ỷ ỷ Ỹ ỹ Ỻ ỻ Ỿ'
for c in s.split():
    n = unicodedata.name(c)#.split()
    if ' AND ' in n: continue
    if not ' WITH ' in n:
        continue
    h = n.split(' WITH ')[0].split()[-1]
    if 'SMALL' in n:
        h = h.lower()
    m = n.split(' WITH ')[1].replace(' ','_')
    print("'%s':'%s'+%s,"%(c,h,m))


'''



