#!/usr/bin/env python3
"""
Prepare the header file which defines the main font data
"""

from CONFIG         import *
from font_utilities import *

C_SOURCE   = ''
headername = terminal_constants_filename.split('/')[-1].split('.')[0].upper()
C_SOURCE += "#ifndef %s_H\n"%headername
C_SOURCE += "#define %s_H\n"%headername
C_SOURCE += '// This file is automatically generated, do not edit it,\n'
C_SOURCE += '// see ./prepare_fonts/README.md for more information. \n'
C_SOURCE += '\n'
C_SOURCE += '// copy these to the top of the main .ino file\n'
C_SOURCE += '// or include the generated %s\n'%terminal_constants_filename
C_SOURCE += '#define SW (%d)\n'%SCREENW
C_SOURCE += '#define SH (%d)\n'%SCREENH
C_SOURCE += '#define TC (%d)\n'%TERMCOLS
C_SOURCE += '#define TR (%d)\n'%TERMROWS
C_SOURCE += '#define TW (TC*CW)\n'
C_SOURCE += '#define TH (TR*CH)\n'
C_SOURCE += '// Extra width %d\n'%EXTRAW
C_SOURCE += '// Extra height %d\n'%EXTRAH
C_SOURCE += '\n'
C_SOURCE += '// Width, height, daseline, midline, topline of characters\n'
C_SOURCE += '#define CW       (%d)\n'%CW
C_SOURCE += '#define CH       (%d)\n'%CH
C_SOURCE += '#define BASELINE (%d)\n'%BASELINE
C_SOURCE += '#define MIDLINE  (%d)\n'%MIDLINE
C_SOURCE += '#define TOPLINE  (%d)\n'%TOPLINE
C_SOURCE += '\n'
C_SOURCE += '''\
// Masks for extracting subsets of the columns of a character
#define CHARROWMASK    ((1<<CW)-1)
#define CHARLEFTMASK   (CHARROWMASK&~1)
#define CHARRIGHTMASK  (CHARROWMASK&~(1<<(CW-1)))
#define CHARMIDDLEMASK (CHARLEFTMASK&CHARRIGHTMASK)

// Row to split at to left-shift to mimic italic style
#define SPLIT          (MIDLINE+1)

// Return codes for utf-8 parsing and rendering
#define SUCCESS         (0) // Character drawn to screen
#define FAIL            (1) // Unexpected condition, likely a bug
#define NOT_MAPPED      (2) // Codepoint is not a unicode character
#define NOT_IMPLEMENTED (3) // Codepoint mapping hasn't been implemented yet
#define LOADED          (4) // Character bitmap loaded, but not yet drawn

'''




C_SOURCE += '\n'
C_SOURCE += "#endif /*%s_H*/\n"%headername
with open(terminal_constants_filename,'wb') as f:
    f.write(C_SOURCE.encode('utf8'))
    f.flush()
    f.close()





