#ifndef UNICODE_BLOCKS_H
#define UNICODE_BLOCKS_H
// This file is automatically generated, do not edit it,
// see ./prepare_fonts/README.md for more information. 

// The following unicode blocks are supported:
int _latin1supplement(uint16_t c); // 0x00000080-0x000000FF
int _latinextendeda(uint16_t c); // 0x00000100-0x0000017F
int _latinextendedb(uint16_t c); // 0x00000180-0x0000024F
int _spacingmodifierletters(uint16_t c); // 0x000002B0-0x000002FF
int _combiningdiacriticalmarks(uint16_t c); // 0x00000300-0x0000036F
int _greekandcoptic(uint16_t c); // 0x00000370-0x000003FF
int _cyrillic(uint16_t c); // 0x00000400-0x000004FF
int _latinextendedadditional(uint16_t c); // 0x00001E00-0x00001EFF
int _generalpunctuation(uint16_t c); // 0x00002000-0x0000206F
int _superscriptsandsubscripts(uint16_t c); // 0x00002070-0x0000209F
int _currencysymbols(uint16_t c); // 0x000020A0-0x000020CF
int _letterlikesymbols(uint16_t c); // 0x00002100-0x0000214F
int _arrows(uint16_t c); // 0x00002190-0x000021FF
int _mathematicaloperators(uint16_t c); // 0x00002200-0x000022FF
int _miscellaneoustechnical(uint16_t c); // 0x00002300-0x000023FF
int _enclosedalphanumerics(uint16_t c); // 0x00002460-0x000024FF
int _boxdrawing(uint16_t c); // 0x00002500-0x0000257F
int _blockelements(uint16_t c); // 0x00002580-0x0000259F
int _geometricshapes(uint16_t c); // 0x000025A0-0x000025FF
int _braillepatterns(uint16_t c); // 0x00002800-0x000028FF
int _mathematicalalphanumericsymbols(uint16_t c); // 0x0001D400-0x0001D7FF
int _symbolsforlegacycomputing(uint16_t c); // 0x0001FB00-0x0001FBFF

// Number of blocks defined
#define NBLOCKS (22)

// Starting unicode point of each defined block, divided by 16
static const uint16_t block_starts_x16[] PROGMEM = {0x8,0x10,0x18,0x2B,0x30,0x37,0x40,0x1E0,0x200,0x207,0x20A,0x210,0x219,0x220,0x230,0x246,0x250,0x258,0x25A,0x280,0x1D40,0x1FB0,};

// Number of codepoints in each block, divided by 16
static const uint8_t block_lengths_x16[] PROGMEM = {0x8,0x8,0xD,0x5,0x7,0x9,0x10,0x10,0x7,0x3,0x3,0x5,0x7,0x10,0x10,0xA,0x8,0x2,0x6,0x10,0x40,0x10,};

// Function pointers to subroutines to handle each block
static int(*const unicode_block[])(uint16_t) = {_latin1supplement,_latinextendeda,_latinextendedb,_spacingmodifierletters,_combiningdiacriticalmarks,_greekandcoptic,_cyrillic,  _latinextendedadditional,_generalpunctuation,_superscriptsandsubscripts,_currencysymbols,_letterlikesymbols,_arrows,_mathematicaloperators,_miscellaneoustechnical,
  _enclosedalphanumerics,_boxdrawing,_blockelements,_geometricshapes,_braillepatterns,_mathematicalalphanumericsymbols,_symbolsforlegacycomputing,};

// Last supported row in unicode tables
#define LASTROW (0x1FBF)

#endif /*UNICODE_BLOCKS_H*/
