#!/usr/bin/env python3
"""
Prepare the header file which defines the main font data
"""

from CONFIG         import *
from font_utilities     import *

C_SOURCE   = ''
headername = main_font_filename.split('/')[-1].split('.')[0].upper()
C_SOURCE += "#ifndef %s_H\n"%headername
C_SOURCE += "#define %s_H\n"%headername
C_SOURCE += '// This file is automatically generated, do not edit it,\n'
C_SOURCE += '// see ./prepare_fonts/README.md for more information. \n'
C_SOURCE += '\n'
C_SOURCE += '''
////////////////////////////////////////////////////////////////////////////////
// No need to pollute workspace with a proliferation of separate C and H files!
// 
// This header contains data. 
// To avoid multiple definitions, Include it in only one C file, (before the
// data in it is used).
'''
C_SOURCE += '\n'
C_SOURCE += '''#ifdef __AVR__
 #include <avr/io.h>
 #include <avr/pgmspace.h>
#elif defined(ESP8266)
 #include <pgmspace.h>
#else
 #define PROGMEM
#endif\n'''
C_SOURCE += '\n'
C_SOURCE += pack_font(main_glyph_image_filename, CW, CH, PADLEFT=1, PADABOVE=1)
C_SOURCE += '\n\n'
C_SOURCE += pack_font(boxdrawing_image_filename,CW,CH)
C_SOURCE += '\n'
C_SOURCE += "#endif /*%s_H*/\n"%headername

with open(main_font_filename,'wb') as f:
    f.write(C_SOURCE.encode('utf8'))
    f.flush()
    f.close()

